= Learn Strategies

== Have a good Studygroup

* Watch out not to go to deep into those "_rabbit holes_".
** Meaning, not get lost in details which are not related to the *topic* at hand
** It might be interesting sometimes, but *focus* and time-efficiency are more important.

== General Study Tips

* Chapter 9:
** Sleep immediately (few hours) after learning.
** Recalling (active) is better than studying/reading (passive).
** Elaborative encoding: "How you place new information into your network of associations has a big effect on your ability to retrieve it."
** Self-generated retrieval cues, rather than other-generated improves retrieval.
** Effect on context: Learn and exam in same room, cues help us to remember. (encoding context == retrieval context)

Advice from textbook:

* Don't passively highlight or copy passages as you read for later rereading. Focus on the ideas, not the author's exact words.
* Constantly ask yourself questions such as these:
** Do I understand the idea that the author is trying to convey here?
** Do I agree with it?
** Is it relevant to my own life experiences? (Research has shown that people remember new information better when they relate it to themselves)
** Has the author given evidence supporting it?
** Does the evidence seem reasonable?
** How is this idea relevant to the larger issues of the chapter?
* As you ask such questions, jot down notes in the margins that bear on your answers, such as:
** "This idea seems similar to ..."
** "I don't understand what my instructor means by ..."
* Through this active process, you will encode the material in a far richer and more lasting way than you could accomplish by simple rereading. In the process, you will also generate questions to ask other students or your instructor.

// TODO study tips => https://www.youtube.com/watch?v=eVlvxHJdql8

== Cognitive Psychology says...

* *Actively process* over passively rereading.
* Understand the *meaning*, question it.
* Build up new *associations*, connect to other knowledge and personal experiences.

== Learn to remember

. *Read* the book
. *Close* it
. *Write* down what i remember
. *Compare* (mark red what is missing/wrong)
. _Do it again some other time_
