= Clinical Psychology 1

== Structure

* link:thema1/index.html[Thema 1 - Frames of reference]
* link:thema2/index.html[Thema 2 - Classification and diagnosis]
* link:https://youlearn.ou.nl/web/pb0104212234/cursus/-/coursenavigator/314974801?_nl_ou_dlwo_courseview_WAR_nloudlwocourseplanportlet__facesViewIdRender=%2Fxhtml%2Fviewer%2FcourseNavigator.xhtml[Masterclass] - Open begin march, duration 4 days
* Exam 1 (first 10 chapters of the book, interviews, masterclass articles)
* link:thema3/index.html[Thema 3 - Psychopathology for adults]
* link:thema4/index.html[Thema 4 - Personality theory & disorders]
* Exam 2

== Goal

It is expected that after the course the student is able to answer the following:

. De *drie modellen* als antwoord op de vraag naar de grens tussen '*gezondheid*' en '*ziekte*' kunt beschrijven en deze kritisch kunt *evalueren*.
. De *zes benaderingen* (=approaches) voor het ontstaan en voortbestaan van psychopathologische stoornissen kunt *beschrijven en toepassen*, verschillende *concepten* binnen deze zes benaderingen kunt reproduceren en de zes benaderingen kritisch kunt *evalueren*.
. Het *nut* van de theorie kunt *beargumenteren*.
. De *DSM-5* als classificatiesysteem van psychopathologische stoornissen kunt *beschrijven en bekritiseren*.
. De *diagnostische methode* kunt beschrijven en bekritiseren.
. De problemen bij *informatieverwerking* van depressie mensen en de *behandeling* van mensen met ADHD, autisme en dementie kunt beschrijven.
. De belangrijkste *symptomen* van de verschillende psychopathologische stoornissen zoals beschreven in de *DSM-5* kunt reproduceren.
. De wetenschappelijke stand van zaken wat betreft de *comorbiditeit, epidemiologie, etiologie* bij de verschillende psychopathologische stoornissen kunt benoemen.
. De *methoden* en de *effectiviteit* van de *diagnostiek en behandelingsvormen* die worden toegepast bij de verschillende psychopathologische stoornissen kunt reproduceren.
. Psychologische *casussen* (=cases) over stoornissen kunt *interpreteren* en de *diagnose en behandeling* daarvan kunt analyseren
. De theorie over *persoonlijkheidstrekken* (=personality traits) en de verschillende concepten binnen deze theorie kunt beschrijven.
