= Selftest Chapter 10

== Multiple Choice

. Hoe noemt men de *interviewvorm* waarbij een psycholoog informatie over een cliënt inwint bij de *partner of ouders* van die cliënt?
.. familieanamnese
.. auto-anamnese
.. indirecte anamnese
.. hetero-anamnese
** [hiddenAnswer]#d.#

. Voor de *gestructureerde interviews* geldt dat
.. de *betrouwbaarheid* dikwijls *laag* is.
.. zij *betrekking* hebben op (slechts) *één onderwerp* of probleemgebied.
.. interviewers vaak van tevoren moeten worden *getraind* in de uitvoering van een interview.
.. de informatie die deze interviews opleveren in sterke mate wordt *beïnvloed* door de *theoretische achtergrond* van de psycholoog.
** [hiddenAnswer]#c.#

. Bij welke diagnostische methode vormt *reactiviteit* met name een groot probleem?
.. bij vragenlijstonderzoek
.. bij projectieve methoden
.. bij gedragsobservatie
.. bij het klinisch interview
** [hiddenAnswer]#c.#

. Welke van de volgende beweringen over de Symptom Check List (*SCL-90*) is *niet juist*?
.. De SCL-90 wordt vaak gebruikt in ons *taalgebied*.
.. De SCL-90 meet onder andere *hostiliteit en angst*.
.. De SCL-90 is een *multidimensioneel instrument*.
.. De SCL-90 meet relatief stabiele persoonlijkheidseigenschappen.
** [hiddenAnswer]#d.#

. Een klinisch psycholoog heeft bij een cliënt een intelligentietest afgenomen. Hij vergelijkt de scores die de cliënt op *stabiele* subtests heeft behaald, met diens scores op de *minst stabiele* subtests. In een klinisch-psychologische context wordt deze methode gebruikt om
.. de mogelijkheid van *intelligentieverval* te onderzoeken.
.. te onderzoeken of problemen van een client in de werksituatie of in de relationele sfeer voortvloeien uit *vaardigheidstekorten* op specifieke gebieden.
.. de *emotionele en intellectuele* labiliteit van een cliënt te kunnen beoordelen.
.. *zwakbegaafdheid* vast te kunnen stellen.
** [hiddenAnswer]#a.#

. Bij projectieve methoden kunnen verschillende procedures worden toegepast. Welke van de volgende taken is *geen* voorbeeld van een *projectieve test* of methode?
.. een test waarbij de cliënt de opdracht krijgt *specifieke patronen te vormen* van blokken
.. een methode waarbij de cliënt een *verhaal* moet vertellen bij een plaat
.. een test waarbij een cliënt *zinnen* moet *aanvullen*
.. een methode waarbij de cliënt de opdracht krijgt om een *boom te tekenen*
** [hiddenAnswer]#a.#

. Welke van de volgende stellingen is *juist*?
.. Neuropsychologische diagnostiek is vaak gericht op de *informatieverwerking* en op de stoornissen die daarin kunnen optreden.
.. Het belangrijkste doel van neuropsychologische diagnostiek is het met behulp van gedragsgegevens opsporen van afwijkingen in de *hersenen*.
.. Door *somatisch onderzoek* te verrichten, vergroten neuropsychologen de betrouwbaarheid van hun diagnose.
.. Neuropsychologisch onderzoek kan niet worden gebruikt voor voor de *differentiële diagnostiek*.
** [hiddenAnswer]#a.#

. Er bestaan *zes klassen diagnostische instrumenten*, namelijk: +
1) klinisch interview 2) gedragsobservatie 3) persoonlijkheids- en klachtenvragenlijsten 4) intelligentietesten 5) projectieve methoden 6) neuropsychologisch onderzoek +
Hieronder vindt u *twaalf voorbeelden* van diagnostische instrumenten. Welk instrument behoort tot welke klasse instrument (per klasse noemt u twee diagnostische instrumenten)? +
a) Bourdon-Wiersma-test b) elektronische dagboekjes c) Hamilton Rating Scale for Depression d) Rorschach e) Thematic Apperception Test f) Directe observatie g) Wisconsin Card Sorting Test h) GIT i) SCID j) MMPI k) WAIS l) NEO-P-IR
.. 1) c + i; 2) b + f; 3) j+ l; 4) k + h; 5) d + e; 6) a + g
.. 1) b + g; 2) a + f; 3) a + c ; 4) i + k ; 5) b + h; 6) g + i
.. 1: b + c; 2: d + h; 3) i + l; 4) j + k; 5) a + e; 6) a + h
.. 1) a + e ; 2) c + i; 3) b + g; 4) f + k ; 5) h + j; 6) c + d
** [hiddenAnswer]#a.#


== Free Text

. Er zijn veel verschillende diagnostische methoden die ingezet kunnen worden. Noem zeven kenmerken waar diagnostische methoden onderling in kunnen verschillen en geef bij ieder kenmerk een voorbeeld.
** [hiddenAnswer]#xxx.#

. Benoem zeven aspecten waarop de COTAN de kwaliteitsbeoordeling van diagnostische instrumenten baseert.
** [hiddenAnswer]#xxx.#

. In een open interview zijn de vorm en de inhoud van het gesprek vrij. Toch komt een aantal onderwerpen vaak aan de orde in open interviews. Er kleven diverse nadelen aan open interviews ten opzichte van semigestructureerde interviews. Benoem vijf onderwerpen die vaak aan bod komen in open interviews. Benoem daarnaast een belangrijk voordeel van open interviews en het belangrijkste nadeel van open interviews ten opzichte van semigestructureerde interviews.

** [hiddenAnswer]#xxx.#

. Benoem de zes klassen diagnostische instrumenten die kunnen worden ingezet en benoem kort het belangrijkste doel waarvoor elk van deze zes klassen instrumenten wordt ingezet (per diagnostisch instrument max. 50 woorden).
** [hiddenAnswer]#xxx.#
