= Science

"_Science is my religion, logic my god._"

== Method

The scientific method has five basic steps, plus one feedback step:

. Make an *observation*.
. Ask a *question*, basically a best-guess.
. Form a *hypothesis*, or testable explanation.
. Make a *prediction* based on the hypothesis.
. *Test*/verify the prediction.

*Iterate*: use the results to make new hypotheses or predictions.

== Versus Pseudoscience

"_When entering the lab, a good scientist leaves his hat at the door_."

[width="100%"]
|=======
|Science |Pseudoscience

|Follows *evidence* wherever it leads. +
"_Let yourself be surprised._" +
Just like Sherlock Holmes: First search for evidence, then draw conclusion.
| Starts with a conclusion, then works backwards to confirm (*confirmation bias*).

| Embraces *criticism*. +
"_Kill my baby!_" Welcoming any attempt to destroy the hypothesis to harden it.
| Hostile to criticism. +
"_Don't ever question god's authority_!"

| Uses *precise terminology* with clear definitions.
| Uses *vague jargon* to confuse and evade. +
"_Energy, Qi or Chakras.
And nowadays abuses quantum physics._"

| Claims are *conservative* and tentative.
| *Grandiose claims* that go beyond the evidence.

| Properly considers *all evidence* and arguments.
| *Cherry picks* only favorable evidence, relies on testimonials or weak evidence.

| Use rigorous and *repeatable methods*.
| Uses *flawed* methods with unrepeatable results. +
"_The influence of some higher energy makes it not testable._"

| Engages with peers and *community*.
| Lone mavericks working in *isolation*. +
"_Moses from the hill, mormons leader looking into his hat_."

| Follows careful and valid *logic*.
| Uses *inconsistent* and invalid logic.
(Cognitive Dissonance) "_Just feel the truth_."

| *Changes* with new evidence.
(Dunning Kruger Effect) +
"_Be honest about not knowing_".
| *Dogmatic* and unyielding.

|=======

== Personal Understanding

* When entering the lab, leave the hat at the door. Meaning *detach* from any desire. Subjective, personal, ego-driven motivation should be left out as much as possible. Any self-identification with interests, occupation, politics, country, sex,... don't matter.
* Let yourself be *surprised*. Yet again, not wanting/desire any specific outcome. Seeking for truth rather comfort (confirming yourself).
* Have the courage to *disprove* yourself. Follow logical conclusions rather (subconscious) self-betrayal.
* Empirical data over personal stories and experiences. Objective measures give more confidence and certainty.
* Always have an *open mind*. Give even the most abstruse theories space to be proven. Remember: We had been wrong so many times in history, why not also this time? Any esoteric claims may have some scientific base somewhere, by an open mind they can be found.
* Give all positions a *fair chance* by enumerate all pros and cons of them, and only after that evaluate by weighting the arguments, ultimately deciding for one side.