= Thema 1 - Clinical theories and frames of reference

Chapter 1-8 (150 pages):

. About clinical psychology
. Neurobiological approach
. Learning theory approach
. Cognitive approach
. Psychoanalytical approach
. Humanistic approach
. Systemic approach
. Usefulness of theories

== Chapter 1 - About clinical psychology

See link:zelftoets1[zelftoets].

The greek word _klinè_ means "bed". So one could easily assume a clinical psychologists work mostly in a hospital, but that's not necessarily the case. Also most of the people associate the word "psychology" with this specific area of "clinical psychology", which is not a surprise as they represent the biggest group.

What is ab/normal in regard to behavior, thoughts and emotions? Where is the border between health and sickness?

In the US, "clinical psychology" is often also referred to as "abnormal psychology". Indicating that it deals with (negative) deviating behavior from a specific norm, which results in difficulties for the person and its environment.

=== Areas of clinical psychology

==== Subdisciplines

Psychology can be divided into several subdisciplines within the two big areas of basic and more application oriented disciplines:

. Basic disciplines:
** Functional ("Functieleer")
** Developmental Psychology
** Social Psychology
** Personality
** Methodology
. Application-oriented disciplines:
** Clinical-/Healthpsychology
** Work-/Organisationpsychology
** Educationpsychology ("Onderwijs")

==== Definitions

"_... bezighoudt met afwijkend, slecht-aangepast en abnormaal ... gedrag. ... diagnose, classificatie, behandeling, preventie en onderzoek._" (Reber, 2004, p. 331)

"_... integrates science, theory and practice to understand, predict, and alleviate maladjustment, disability and discomfort ... promote human adaption, adjustment, and personal development. ... focuses on the intellectual, emotional, biological, psychological, social and behavior aspects ..._" (American Psychological Association, 2013)

"_... gedrag van de meens in relatie tot zijn ervaren gezondheid empirisch wordt onderzocht, ..._" (Winnubst, Schnabel, Van den Bout & Van Son, 1991, p. XI)

"_... rigorous study and applied practice directed toward understanding and improving ... problems of behavior, emotions, or intellect._" (Pomerantz, 2012, p. 5)

==== Norm deviating

Deviating in two aspects:

. Individual person's aspects
** Behavior (excessive drinking)
** Thoughts (compulsive thinking)
** Experiences (extreme fear)
. Relation to others
** E.g. overworried towards kids, or extreme aggressiveness
** These interpersonal-relational deviations have themselves again impact on the innr world of a person
*** E.g. Students avoid contact with others (avoidant behavior), thinks he will never find friends, making him experience emotions of loneliness.

Knowledge of the **basic disciplines** is necessary to understand "normal" psychological functioning (perception, cognition, memory) of the "normal" development, social psychology and personality psychology, in order to identify and understand deviations from the norm.

In the end, the border between normal and abnormal is less obvious.

==== Psychologist vs. Psychiatrist

Both diagnose and treat people with psychological problems. Both can work in the ambulance for example.

There are fundamental **educational differences** though: A psychologist studied psychology (4 years with postgraduate), a psychiatrist has a medical education (6 plus 4 years specialiation). In the Netherlands there is yet another differentiation between a healthcare (general) and clinical (specialized, +1 year) psychologist. A psychologist is better for **empirical research** and methodology, whereas a psychiatrist, with his more profound knowledge about medicine and biological aspects of mental disorders, is allowed to **prescribe drugs**.

=== Aspects of "abnormal" behavior

==== Zeven factors

By Seligman et al:

. **Personal suffering**
** Such as depression, feeling miserable, empty, lifeless; nothing is enjoyable/pleasurable; every day is gray.
. **Dysfunctional behavior**
** Negatively affecting daily functioning and well-being. Function at work and in having satisfying relations.
** E.g.: When fears prevent from leaving the house, or alcoholism creates problems in the family.
. **Irrational / Uncromprehensible behavior**
** Illogical things like from boulima nervosa patients, which vomit after eating; or people with psychosis.
. **Unpredictability / Loss of control**
** We have the need for controlling our own lives and environment. For that, others need to behave consistently.
** Seligman et al differentiate between two types of situations where self-control is lost: 1) Regular behavior shows no effect anymore and 2) observers can't explain the cause of one's behavior.
. **Unconventional/notable behavior**
** We usually use our own (potential) behavior as measurement.
** Outstanding behavior also depends on frequency/amount of a particular behavior.
** Non-conforming and socially undesirable behavior is usually considered pathological.
. **Discomfort evoking behavior**
** Unwritten rules of a culture are overstepped, which evokes uncomfortable feelings ("observer discomfort").
** "_Restregels_": Implicit social expectations, by Scheff, once overstepped, we get aware of them.
** E.g.: Eye contact, approporiate distance while talking, leave spots free in-between in waiting rooms/toilet.
. **Violating moral norms**
** Based on the moral idea of good and bad, whereas "bad" is "abnormal".
** The less the behavior conforms with an ideal image / own idea of optimal functioning, the more abnormal.

PAGE 22, middle

=== Borders between normal and abnormal




== Chapter 2 - Neurobiological approach

See link:zelftoets2[zelftoets].

== Chapter 3 - Learning theory approach

See link:zelftoets3[zelftoets].

* OP ... onvoorwaardelijke prikkel (unconditional)
* OR ... onvoorwaardelijke reactie
* VP ... voorwaardelijke prikkel (conditional)
* VR ... voorwaardelijke reactie

== Chapter 4 - Cognitive approach

See link:zelftoets4[zelftoets].

== Chapter 5 - Psychoanalytical approach

== Chapter 6 - Humanistic approach

== Chapter 7 - Systemic approach

== Chapter 8 - Usefulness of theories
