= Focus Questions

. What was Harlow’s procedure for studying attachment in infant monkeys, and what did he find?
** [hiddenAnswer]#Bar.#

. According to Bowlby, what infant behaviors indicate strong attachment, and why would they have come about in natural selection?
** [hiddenAnswer]#Bar.#

. From an evolutionary perspective, why does attachment strengthen at about 6 to 8 months of age?
** [hiddenAnswer]#Bar.#

. How does the strange-situation test assess the security of attachment?
** [hiddenAnswer]#Bar.#

. What evidence suggests that sensitive parenting correlates with secure attachment and subsequent emotional and social development? How did Ainsworth interpret the correlations, and how else might they be interpreted?
** [hiddenAnswer]#Bar.#

. What experimental evidence supports the theory that sensitive care promotes secure attachment?
** [hiddenAnswer]#Bar.#

. What evidence suggests that some infants are relatively invulnerable to negative effects of insensitive parenting?
** [hiddenAnswer]#Bar.#

. What are some differences in the way cultures care for young infants?
** [hiddenAnswer]#Bar.#

. What observations suggest that hunter-gatherers are highly indulgent towards infants? What parenting styles distinguish the !Kung, Efe and Aka?
** [hiddenAnswer]#Bar.#

. According to Hoffman, how does empathy develop during infancy and early toddlerhood?
** [hiddenAnswer]#Bar.#

. What evidence suggests that young children naturally enjoy giving? How do the !Kung use that enjoyment for moral training?
** [hiddenAnswer]#Bar.#

. At about what age and under what conditions do children share?
** [hiddenAnswer]#Bar.#

. What is overimitation, who engages in it, and why might it be adaptive?
** [hiddenAnswer]#Bar.#

. What evidence is there that children learn new skills from watching other children?
** [hiddenAnswer]#Bar.#

. What are four general parenting styles psychologists have identified, and how do they affect children’s psychological development?
** [hiddenAnswer]#Bar.#

. How do observations of two Mexican villages illustrate the role of playing in transmitting cultural skills and values from one generation to the next? How might play promote cultural advancement?
** [hiddenAnswer]#Bar.#

. What ideas did Piaget and Vygotsky present concerning the value of play in social development? What evidence supports their ideas?
** [hiddenAnswer]#Bar.#

. What features of age-mixed play may make it particularly valuable to a child’s development?
** [hiddenAnswer]#Bar.#

. What are some of the ways that girls and boys are treated differently by adults in our culture, and how might such treatment promote different developmental consequences?
** [hiddenAnswer]#Bar.#

. How do children mold themselves according to their understanding of gender differences?
** [hiddenAnswer]#Bar.#

. What function might children’s self-segregation by gender serve? In our culture, why might boys avoid playing with girls more than the reverse?
** [hiddenAnswer]#Bar.#

. In what ways can girls’ and boys’ peer groups be thought of as separate subcultures? Why might differences in boys’ and girls’ play be greater in age-segregated settings than in age-mixed settings?
** [hiddenAnswer]#Bar.#

. What is the typical nature of so-called adolescent rebellion against parents?
** [hiddenAnswer]#Bar.#

. What evidence suggests that peer pressure can have negative and positive effects? What difference in attitude about peer pressure is reported to exist in China compared to the United States?
** [hiddenAnswer]#Bar.#

. What are two theories about how adolescents’ segregation from adults might contribute to their recklessness and delinquency?
** [hiddenAnswer]#Bar.#

. How have Wilson and Daly explained the recklessness and delinquency of adolescent males in evolutionary terms?
** [hiddenAnswer]#Bar.#

. How did Kohlberg assess moral reasoning? How can his stages be described as the successive broadening of one’s social perspective? How does research using Kohlberg’s system help explain adolescent idealism?
** [hiddenAnswer]#Bar.#

. What correlations have been observed between sex education and rates of teenage pregnancy?
** [hiddenAnswer]#Bar.#

. How can the sex difference in desire for uncommitted sex be explained in evolutionary terms?
** [hiddenAnswer]#Bar.#

. How can sexual restraint and promiscuity, in both sexes, be explained as adaptations to different life conditions? What evidence suggests that the presence or absence of a father at home, during childhood, may tip the balance toward one strategy or the other?
** [hiddenAnswer]#Bar.#

. How is romantic love like infant attachment? What evidence suggests continuity in attachment quality between infancy and adulthood?
** [hiddenAnswer]#Bar.#

. What are some characteristics of happily married couples? Why might marital happiness depend even more on the husband’s capacity to adjust that on the wife’s?
** [hiddenAnswer]#Bar.#

. What evidence suggests that the type of job one has can alter one’s way of thinking and style of parenting and can influence the development of one’s children?
** [hiddenAnswer]#Bar.#

. What difference has been found between husbands’ and wives’ enjoyment of out-of-home and at-home work? How did the researchers explain that difference?
** [hiddenAnswer]#Bar.#

. How does the socioemotional selectivity theory account for elderly people’s generally high satisfaction with life?
** [hiddenAnswer]#Bar.#

. How might selective attention and selective memory contribute to satisfaction in old age?
** [hiddenAnswer]#Bar.#

== Think Critically

. Foo
** [hiddenAnswer]#Bar.#

. Foo
** [hiddenAnswer]#Bar.#

. Foo
** [hiddenAnswer]#Bar.#