= Focus Questions

. How has Western society’s response to people with serious psychological disorders changed over the centuries? What were the goals of the deinstitutionalization movement?
** [hiddenAnswer]#Bar.#

. How do assertive community treatment programs attempt to help the severely mentally
disordered and their families?
** [hiddenAnswer]#Bar.#

. What are the major categories of mental health providers?
** [hiddenAnswer]#Bar.#

. According to a survey conducted in the United States, where do people with psychological disorders typically find treatment, and what types of treatment do they find?
** [hiddenAnswer]#Bar.#

. What is known about the mechanisms, effectiveness, and limitations of drugs used to treat schizophrenia, generalized anxiety and depression?
** [hiddenAnswer]#Bar.#

. What are three different reasons why symptoms of a disorder may decline after being treated with a drug?
** [hiddenAnswer]#Bar.#

. What evidence suggests that only a small percentage of the improvement following drug treatment for depression results from the chemical effects of the drug? Why might the power of suggestion, or expectancy, be especially effective in the treatment of depression?
** [hiddenAnswer]#Bar.#

. Under what conditions and how is ECT used to treat depression?
** [hiddenAnswer]#Bar.#

. How are modern, refined forms of psychosurgery sometimes used today in the treatment of obsessive-compulsive disorder?
** [hiddenAnswer]#Bar.#

. What is the advantage of deep brain stimulation over current forms of psychosurgery?
** [hiddenAnswer]#Bar.#

. According to psychodynamic therapists, what are the underlying sources of psychological disorders?
** [hiddenAnswer]#Bar.#

. According to psychodynamic therapists, what is the relationship between symptoms and disorders?
** [hiddenAnswer]#Bar.#

. How do psychodynamic therapists use patients’ free associations, dreams, and “mistakes” as routes to learn about their unconscious minds?
** [hiddenAnswer]#Bar.#

. In psychodynamic therapy, how do resistance and transference contribute to the therapeutic process?
** [hiddenAnswer]#Bar.#

. According to psychodynamic theories, how do insights into the patient’s unconscious conflicts bring about a cure?
** [hiddenAnswer]#Bar.#

. What is the primary goal of humanistic therapy? How does that goal relate to existentialist philosophy?
** [hiddenAnswer]#Bar.#

. How do the therapist’s nondirective approach, empathic listening, and genuine positive regard contribute to the client’s recovery, according to humanistic therapist?
** [hiddenAnswer]#Bar.#

. How has contingency management been used to improve children’s behaviour and motivate abstinence in drug abusers?
** [hiddenAnswer]#Bar.#

. What is the theoretical rationale for treating specific phobias by exposing clients to the eared objects or situations?
** [hiddenAnswer]#Bar.#

. What are three ways of exposing clients to feared objects or situations, and what are the advantages of each?
** [hiddenAnswer]#Bar.#

. How did virtual exposure treatment help Miss Muffet overcome her fear of spiders?
** [hiddenAnswer]#Bar.#

. How is behaviour therapy distinguished from cognitive therapy?
** [hiddenAnswer]#Bar.#

. According to cognitive therapists, what is the source of clients’ behavioural and emotional problems?
** [hiddenAnswer]#Bar.#

. How did Ellis explain people’s negative emotions in terms of their irrational beliefs?
** [hiddenAnswer]#Bar.#

. What is the purpose of homework in cognitive therapy?
** [hiddenAnswer]#Bar.#

. In what sense is a cognitive therapist initially a teacher and later a consultant?
** [hiddenAnswer]#Bar.#

. How does Beck’s treatment of a depressed woman illustrate his approach to identifying and correcting maladaptive, automatic thoughts?
** [hiddenAnswer]#Bar.#

. Why must we rely on experiments rather than case studies to assess the effectiveness of psychotherapy?
** [hiddenAnswer]#Bar.#

. How did an experiment in Philadelphia demonstrate the effectiveness of behaviour therapy and psychodynamic therapy?
** [hiddenAnswer]#Bar.#

. What is the evidence that psychotherapy works and that for some disorders it works as well as, or better than, standard drug treatments?
** [hiddenAnswer]#Bar.#

. What general conclusions have been drawn from research comparing different forms of psychotherapy?
** [hiddenAnswer]#Bar.#

. How are support, hope, and motivation provided within the framework of standard types of psychotherapy? What evidence suggests that these common factors contribute to the therapy’s effectiveness?
** [hiddenAnswer]#Bar.#

== Think Critically

. Why would a knowledge of research methodology be important for evaluating the effectiveness of different forms of treatments for psychological disorders?
** [hiddenAnswer]#Bar.#

. By some estimates, prisons may be the largest mental health providers in the United States. What implications, if any, does this have for the diagnosis and treatment of people with psychological disorders?
** [hiddenAnswer]#Bar.#

. Is psychotherapy a science? Has science shown that psychotherapy works? Give reasons for your answers.
** [hiddenAnswer]#Bar.#