= Chapter 4 - Neural

== Opdracht 4.1

Hoe zijn neuronen opgebouwd.

== Opdracht 4.2

Vroeger konden we niet veel meer dan ons verwonderen over de vreemde afwijkingen die mensen met hersenletsel soms vertoonden. Tegenwoordig hebben we gelukkig veel meer technologie tot onze beschikking en kunnen we het functionerende brein op diverse manieren bestuderen. In hoofdstuk 4 van het handboek worden diverse van deze technieken besproken. Maak deze opdracht om uw kennis van deze technieken te toetsen.

Hieronder staat een aantal technieken opgesomd die gebruikt kunnen worden om de hersenen te bestuderen. Tevens vindt u een aantal beschrijvingen van een techniek opgesomd. De opdracht is om de juiste naam (cijfer) bij de juiste beschrijving (letter) te plaatsen.


. Positron Emission Tomography (PET)
. Electroencephalography (EEG)
. Functional Magnetic Resonance Imaging (fMRI)
. Transcranial Magnetic Simulation (TMS)
. Magnetic Resonance Imaging (MRI)

[loweralpha,start=1]
. het bestuderen van de metabolische activiteit in de hersenen door veranderingen in bloedtoevoer naar actieve hersengebieden te meten
. het meten van de elektrische activiteit van de cortex door middel van het plaatsen van elektronen op de schedel
. het lokaliseren van hersenfuncties door het tijdelijk onderbreken van de elektrische activiteit in een bepaald gebied met behulp van een magnetisch veld
. het bestuderen van de metabolische activiteit van glucose of zuurstof in de hersenen na het toedienen van een radioactieve stof
. beeldvorming van de anatomie van de hersenen waarbij een sterk magnetisch veld en radiogolven worden gebruikt.

Het juiste antwoord is:

[hiddenAnswer]#1-d, 2-b, 3-a, 4-c, 5-e +
Positron Emission Tomography (PET): het bestuderen van de metabolische activiteit van glucose of zuurstof in de hersenen na het toedienen van een radioactieve stof +
Electroencephalography (EEG): het meten van de elektrische activiteit van de cortex door middel van het plaatsen van elektronen op de schedel +
Functional Magnetic Resonance Imaging (fMRI): het bestuderen van de metabolische activiteit in de hersenen door veranderingen in bloedtoevoer naar actieve hersengebieden te meten +
Transcranial Magnetic Simulation (TMS): het lokaliseren van hersenfuncties door het tijdelijk onderbreken van de elektrische activiteit in een bepaald gebied met behulp van een magnetisch veld +
Magnetic Resonance Imaging (MRI): beeldvorming van de anatomie van de hersenen waarbij een sterk magnetisch veld en radiogolven worden gebruikt.#

== Opdracht 4.3

Maak een lijst met delen van het zenuwstelsel (voor zover u die tot nu toe heeft bestudeerd) die actief zijn tijdens de bezigheid die hierboven wordt beschreven. Zet er ook kort bij wat de functie is van elk specifiek deel van het (centrale) zenuwstelsel dat u bespreekt.

== Opdracht 4.4

Wat is het verschil tussen afasie van Wernicke en afasie van Broca? Benoem in uw antwoord waar het gebied ligt dat verantwoordelijk is voor de afasie en hoe u mensen met deze afasie zou kunnen herkennen.

[hiddenAnswer]#Bij afasie van Wernicke is er een beschadiging in de temporaalkwab van de linkerhemisfeer, vlakbij de primaire auditieve cortex. Dit gebied is betrokken bij het vertalen van de klank van woorden naar een betekenis en het zoeken van woorden, via verbindingen naar associatiegebieden, die nodig zijn om hetgeen iemand wil zeggen ook echt te kunnen zeggen. Afasie van Wernicke wordt ook wel ‘fluent’ afasie genoemd. Het taalgebruik van mensen met afasie van Wernicke is namelijk vaak vloeiend en de zinnen die ze maken zijn lang. Grammaticaal kloppen de zinnen echter vaak niet. Ze hebben moeite met het vinden van de juiste woorden om uit te drukken wat ze bedoelen. Mensen met een afasie van Wernicke zijn zich vaak minder bewust van fouten die ze maken. +
Bij afasie van Broca is er een beschadiging in de frontaalkwab van de linkerhemisfeer, net voor de primaire motorcortex. De primaire motorcortex controleert bewegingen van de tong en andere spieren die gebruikt worden bij het spreken. Afasie van Broca wordt ook wel ‘non-fluent’ afasie genoemd. Het taalgebruik van mensen met afasie van Broca is namelijk niet vloeiend en in telegramstijl, zo min mogelijk woorden worden gebruikt om de boodschap over te brengen. De zinnen bestaan dan ook met name uit werkwoorden en zelfstandige naamwoorden en zijn vaak niet langer dan drie of vier woorden. Mensen met afasie van Broca zijn zich meestal erg goed bewust van hun afasie.#

'''

link:index.html[Alle opdrachten]
