= Welcome to the PsyWiki ❤️🤓

"_In the seek of truth, not of comfort._"

== About

The *purpose* of this wiki is primarily to collect, organize, and summarize all the knowledge acquired during my study at the link:https://www.ou.nl[Open University Netherlands]. Yet, the content started to go way beyond that, and contains now material which simply caught my interest. May you experience the same pleasure as I did while studying the vast knowledge about the human mind. Never stop to think deeply, my fellow philosopher.

== Content

Currently, *most of the content* exists for the following subjects:

* link:lva_introduction/index.html[Introduction to Psychology]
* link:lva_clinical/index.html[Clinical Psychology]
* link:lva_social/index.html[Social Psychology]

Everything else is mostly link:universiteit/index.html[university related] content, besides a list of link:people/index.html[very important people], as well as a collection of link:phenomena/index.html[phenomena] containing fascinating studies, experiments, real life cases, biases and other fascinating stuff.

The link:meta/index.html[meta discussions] cover topics not directly related to psychology but still touch it on another level.
For any further reading have a look at the collection of link:resources/index.html[resources].

*Work in progress* is currently the page about the different link:schools/index.html[schools in psychology].
