= Focus Questions

. In what sense are people *natural psychologists*?
** [hiddenAnswer]#We are all naive psychologists, applying folk psychology by understanding naturally the psychological world. Even without formal training we sometimes accurately observe/judge other's behavior.#

. What evidence supports the existence of a *person bias* in attributions?
** [hiddenAnswer]#For example: I give a paper to read to someone which has opinion X, I will rate that person's opinion to be X, although he had no choice in the paper to read. Or when we observe a person in uniform (police, doctor, teacher) carrying out their duties, we attribute the action to the personality, ignoring the constraints of that role which he must act upon.#

. (a) Why is the person bias often called the *fundamental attribution error*? (b) In what *conditions* does the bias most often occur?
** [hiddenAnswer]#(a) Because it isi so pervasive and strong, underlying many other social-psychological phenomena (something which actually might not be the case). (b) When being told that the task is to judge someone's personality.#

. What logic and evidence suggest that the person bias may be a product of *Western culture* and may not exist in Eastern culture?
** [hiddenAnswer]#When asking people in US and India to explain a person's behavior, US people attribute more to personality, whereas only true for adults, not for children. Thus: It's the environment shaping us. Explanation could be that Western cultures emphasize personal independence (over interdependence).#

. How have researchers documented biasing effects of *physical attractiveness* on perceptions of personality?
** [hiddenAnswer]#Teachers were given pictures of unknown children and to rate their intelligence/achievement. Attractive children were rated better (brighter, more successful). Also judges give longer prison sentences to ugly people for comparable crimes. PS: This is more a thing in the West than in the East.#

. How have researchers documented biasing effects of a *babyish* versus a *mature-looking face* and what practical *consequences* have been shown to result from this bias?
** [hiddenAnswer]#By showing pictures of political candidates only for 1 second and they predicted the outcome correctly. Thus: Mature-faces look more competent, thus will be voted more likely. Also, manipulating president's faces making them look more babish would decline their perceived leadership qualities. Infant-like features of animals (rabbits, pandas) make us see them as more cute, innocent and needing care; us over-generalizing these features on animals, babies and adults. Wanting them to comfort and cuddle, but not to have them as our leaders.#

. (a) What evidence suggests that *strangers* who meet on the *internet* like each other more than do strangers who meet in person? (b) How might this phenomenon be *explained*?
** [hiddenAnswer]#(a) In a "blind speed date" situation in a chat room, compared to face-to-face encounters, it was shown that the pairs liked each other more at the second date when the first one was via the internet. (b) Internet dates are more intimate, revealing the "true self". Anonymity, lack of visual/auditory contact, reducing social anxiety; freeing to reveal more of themselves. Physical attractiveness bias can't kick in. Communication stays, and stays unaffected by negative judgements/anxieties (based on physical features). Better emotional bond when first see at second date.#

. According to Cooley, what is the *looking-glass self* with which we evaluate ourselves?
** [hiddenAnswer]#We build our self-concepts based on what we infer what others think of us from their reactions. Opinions/attitudes about ourself affect opinions/attitudes of others.#

. (a) What are *Pygmalion effects* in psychology, and (b) how were such effects demonstrated in elementary *school* classrooms?
** [hiddenAnswer]#(a) Also called "Self-fulfilling prophecies". How we behave towards people (based on our opinions/expectations of them) will shape their understanding of themselves, and thus ultimately also their behavior. (b) Students got randomly grouped into "smarter ones", and only teachers, not students, were told so. After some time, these students indeed performed better. Teachers were warmer to them, gave more time to solve difficult problems, gave more challenging work, noticed/reinforced self-initiated efforts, thus creating (un)consciously better learning environments. Also the students started to change their self-concepts: more capable academically, thus working harder to live up to that perception.#

. (a) What is the *sociometer theory* of self-esteem, and (b) what *evidence* supports it?
** [hiddenAnswer]#(a) Self-esteem is dictated by which degree we are accepted/rejected by others; other words: judgements derived from the perception of other's towards us. (b) Self-esteem correlates strongly with believe being accepted/rejected by others. Self-esteem increases after praise/social acceptance and decreased after social rejection. Test result has bigger impact if others will know about it.#

. (a) What is some evidence that people construct a *self-concept* by comparing themselves with a *reference group*? (b) How can a change in reference group can alter *self-esteem*?
** [hiddenAnswer]#(a) Children in racially mixed classrooms more often mention their race, especially when in a minority. When being unusually tall/short, height was mentioned more often. Opposite-gender siblings mentioned their own gender more frequently. (b) This is shown by the "big-fish-in-small-pond effect": Self-esteem can be crushed once the reference group is much better than before, and vice versa. (It all depends with whom you compare yourself with.)#

. What are two means by which people build and maintain *inflated views* of themselves?
** [hiddenAnswer]#Instead the person bias, the self-serving attributional bias kicks in: Success attributed to inner qualities, failure to external circumstances. Or by selective memory: We remember positive events/success better in long-term memory, only for ourselves, not for others; and it's stronger in older adults.#

. What is the difference between *implicit and explicit attitudes* in their manner of influencing behaviour?
** [hiddenAnswer]#Attitude = Belief/opinion with an evaluative component (good/bad judgement). For implicit attitudes we listen to our gut feeling, for explicit attitudes we need to think about what we are doing.#

. How does *cognitive dissonance* theory explain people's *attraction* to some information and *avoidance* of other information?
** [hiddenAnswer]#We tend to avoid information which conflicts with our opinions/beliefs as it creates discomfort, and feel attracted to information that supports/confirms us and thus creating comfort.#

. How does the cognitive dissonance theory explain why people are more *confident* of a *decision just after* they have made it than just before?
** [hiddenAnswer]#Once we chose for an irreversible option we rather set aside our doubts, otherwise we would feel uncomfortable. E.g. horse betters before/after the bet speaking about horse; or voters before/after polling place speaking about candidate.#

. (a) In theory, why should the *insufficient-justification effect* work best when there is *minimal incentive* for the action and the action is *freely* chosen? (b) How was this theory *verified* by two classic experiments?
** [hiddenAnswer]#(a) Low reward otherwise the excuse can be made because of the reward itself and no lie is necessary. Freely chosen because otherwise we can easily relieve dissonance by saying "I was forced to". (b) Subjects had to hire a person for a very boring job offering either very little money (claiming to themselves the job was nice) or very much money (honest about the boring job). In another experiment subjects had to or were asked to write an essay about a topic they didn't support, and those who had choice shifted their opinion favoring the subject suddenly.#

. (a) What is the distinction among public, private and implicit *stereotypes*? (b) What are two means by which researchers *identify* implicit stereotypes?
** [hiddenAnswer]#(a) Public = What we say to others. Private = Consciously believe but not say. Implicit = Automatic judgements/actions. (b) Either through an "implicit association test", were terms/pictures need to be put in one box or another and time is being kept track off, showing that some associations are being down slower, more difficult, therefore less of a stereotype. No other means known. #

. What evidence suggests that *implicit prejudice* can cause police officers to *shoot at black* suspects more readily than at white suspects?
** [hiddenAnswer]#In VR, officers had to decide based on black or white faces, to shoot or not at people with a gun or without a gun. Results have shown they are significantly more likely to wrongly shoot when the person was black. Yet it can be practiced (immediate feedback) to make that racial bias go away. Also when being shown black, rather white, faces, subjects categorized threatening objects faster and more correctly.#

. What sorts of learning experiences are most effective in *reducing* (a) explicit and (b) implicit prejudice?
** [hiddenAnswer]#(a) Deliberate learning and logic. (b) By classical conditioning these primitive emotions can be changed. Having black friends. Exposure to admirable black people in movies/literature. Positive association with members of the group reduces automatic negative responses toward the group. Or diversity-training reducing explicit as well as implicit prejudice.#

. (a) How does Zajonc's theory explain both *social facilitation* and social *interference*? (b) What *evidence* supports the theory?
** [hiddenAnswer]#(a) When being watched, performance either improves (social facilitation) or gets worse (social interference/inhibition). Explanation is by increase of drive/arousal, increasing effort, facilitating dominant (simple/well-learned) tasks, and interfering with nondominant (complex) actions, where controll/calm/conscious thought/attention is needed. (b) Arousal can be measured (increased heart rate) or reported by people themselves. E.g. professional pool players performed better when observed, and the opposite was the case for beginners. Another experiment showed that when just having learned a new topic, and having to explain it to others, this task would be done better if just have given positive feedback about it, thus boosting confidence; and vice versa.#

. What *evidence* supports the view that *choking* on tests occurs because distracting thoughts interfere with *working memory*?
** [hiddenAnswer]#When subjects were given a test, and told that the success of their team would depend on their individual test, the result would be significantly worse. Same also when being told that they were recorded and afterwards judged based on the recording.#

. (a) How can the activation of a *stereotype influence* test performance? (b) What *evidence* suggests that this effect, like other forms of choking, involves increased anxiety and interference with working memory?
** [hiddenAnswer]#(a) Stereotype threat happens when a person is being told, that the group it belongs to, would perform bad at a test before the test is being taken, and therefore will perform bad; (unconsciously) activating the belief (self-fulfilling prophecy). (b) E.g. telling black people to take a test and claiming it is an intelligence test. Or giving older adults a working-memory tests, while being contrasted to younger adults. Or giving women a math test, or to men while telling them Asians perform better. Or Christians on a science test.#

. (a) How do certain theatrical and political metaphors apply to *impression management*? (b) *Why* do we, as intuitive politicians, want to look "good" to other people?
** [hiddenAnswer]#(a) We perform in front of others to tell a good story, or portray a character, to achieve real-life goals in the end. We need others to cooperate with us, need their approval, and to get that we campaign for ourselves/our interests to get their votes; often unconsciously. (b) We want to be perceived as attractive, friendly, competent, rational, trustworthy and moral; manipulating others to make them more willing to collaborate with us if they see those qualities in us. Perceived modest, understating our virtues. Perceived sincere.#

. What are two classes of reasons why people tend to *conform to examples* set by others?
** [hiddenAnswer]#Informational influence: All cross bridge A, none bridge B, thus its safer to use A. No one eats that leaf, better not eat it, as it might be poisonous. Building upon the information available of previous generations' trial and errors.+
Normative influence: Crossing bridge A because we are the bridge A group and proud of it; you crossing bridge B would look strange, not wanting be part of our group. Thus, the desire to be part of a group, be approved by others. To promote group cohesion and acceptance by the group, otherwise social groups wouldn't exist. Adapt to ideas/myths/habits of the group, generating closeness, promotes acceptance, group functioning as a unit.#

. How did *Asch* demonstrate that a tendency to *conform* can lead people to *disclaim the evidence* of their own eyes?
** [hiddenAnswer]#A subject with some confederates was asked to judge whether a line fits another, an absurdly easy perceptual task. The actors claimed the -clearly- wrong one, and when it was the subjects turn, he would conform with that wrong answer.#

. (a) According to Cialdini, how can *public-service messages* best capitalize on *normative influences*? (b) What *evidence* does he provide for this idea?
** [hiddenAnswer]#(a) When talking about how not to behave, people think that's the normal behavior, thus these messages should always phrased in a positive manner, stating what IS the desired behavior. (b) He aired an advertisment showing people recycling and speaking disapprovingly of a lone person who didn't recycle; a major increase in recycling was detected after that. Another study was a sign in a park telling people how (not) to behave.#

. How can the failure of multiple *bystanders* to help a person in need be explained in terms of informational and normative *influences*?
** [hiddenAnswer]#A collection of individuals is a "unified collection", behaving like one another (mimicing postures, mannerisms, speech style, emotions), and differently than if they were by themselves. Thus, when no one helps a person in need, no one will take the first step, thinking: "If they don't, I won't."#

. (a) What is the value, for group life, of the *spread* of sadness, anger, fear, and laughter from person to person? (b) How might emotional contagion figure into the rise of a *group leader*?
** [hiddenAnswer]#(a) To communicate how to interact with each other; who needs help, is approachable for help, or be avoided. Contagious emotions help to unite a group. Sadness plus empathy leads to helping. Anger with potential allies leads to shared anger and recruitement. Fear spreads, leading to hightened vigilance (=Wachsamkeit), increasing protection/safety. Laughter being the most contagious, creating playful mood, reducing chance feeling offended. (b) Most communication happens in their persuasive facial expressions. They can make people feel similar the way they express themselves.#

. What are some experiments that have demonstrated *group polarization*?
** [hiddenAnswer]#Juries would rate high-guilt cases higher (same for low lower) after the group discussion than before. Being in favor of one political party, going to a party club will likely shift further toward that direction. Or prisoners entering the prison, being around other criminals, leave the prision with less respect for the law when they entered.#

. (a) How did Janis explain some White House policy blunders with his *groupthink* theory? (b) What can groups do to *reduce* the risk of groupthink?
** [hiddenAnswer]#(a) A small group of advisors where more concerned with group unity and pleasing the president, rather examine critically the president's favorite choice; they defended that choice and suppressed criticism of it. (b) Leader refrain from adovating a view himself, instead encourage group to present their own views and challenge one another. Focus on the problem to be solved, rather developing group cohesion.#

. How can the *low-ball sales technique* be explained in terms of cognitive dissonance? What *evidence* supports this explanation?
** [hiddenAnswer]# This technique is about for example selling the product cheap, get a "yes", and then "discovering" it has to be sold more expensive. First the customer says "yes", and then have to reduce cognitiv dissonance by removing doubts about the product. They exaggerate the products' value, to be able to justify to pay the higher price.#

. How can the *foot-in-the-door sales technique* be explained in terms of cognitive dissonance?
** [hiddenAnswer]#This technique will lead to people to agree to a bigger request, once they agreed to a smaller request. By agreeing to the small request, people may think something like "I contributed to it, so I must believe in it" which promotes willingness to make larger donations.#

. How did *Milgram* demonstrate that a remarkably high percentage of people would follow a series of orders to hurt another person?
** [hiddenAnswer]#A subject would be the teacher, asking another person (a confederate) questions, and if answered wrongly having to give electrical shocks. Although they wanted to stop, the researcher insisted to continue, so they obeyed.#

. Why does Milgram's *finding* call for an explanation in terms of the *social situation* rather than in terms of unique characteristics of the subjects?
** [hiddenAnswer]#All kind of people, ages, classes, genders, jobs, ... All of them would comply, so it's not personal. They were also not sadistic, as they didn't show any signs of pleasure. Also when redone today, it yields the same results.#

. How might the high rate of obedience in Milgram's experiments be *explained* in terms of (a) the norm of *obedience*, (b) the experimenter's acceptance of *responsibility*, (c) the *proximity* of the experimenter, (d) the lack of a *model* for rebellion, and (e) the *incremental* nature of the requests?
** [hiddenAnswer]#(a) . (b) . (c) . (d) .#

. (a) How has Milgram's research been *criticized* on grounds of ethics and real-world validity, and (b) how has the research been *defended*?
** [hiddenAnswer]#(a) . (b) .#

. (a) How does *the tragedy of the commons* illustrate the critical importance of social dilemmas to human survival? (b) What are some *examples* of real-world social dilemmas?
** [hiddenAnswer]#(a) . (b) .#

. (a) How have laboratory games demonstrated the human sense of justice and willingness to *punish* even at *personal cost*? (b) How does such behaviour promote *long-term cooperation*?
** [hiddenAnswer]#(a) . (b) .#

. What is some evidence that *social identity* can lead to helping group-mates and hurting those who are not group-mates?
** [hiddenAnswer]#Bar.#

. What changes occurred within and between two groups of boys as a result of *intergroup competitions* at a summer camp?
** [hiddenAnswer]#Bar.#

. How did Sherif and his colleagues succeed in *promoting peace* between the two groups of boys?
** [hiddenAnswer]#(a) . (b) .#

== Think Critically

. What *evidence* was presented for the existence of each of the *biases* presented in the chapter? For example, how do we know that the person bias exists?
** [hiddenAnswer]#Bar.#

. How do you think one's *implicit attitudes* influence one's *explicit* attitudes? If a person displays racial bias on a test of implicit attitudes but not explicit attitudes, is it appropriate to say that person is a racist?
** [hiddenAnswer]#Bar.#

. (a) What *factors* may explain why people experience arousal and a strong drive to do well—leading to either social interference or facilitation— when they know that their performance is *being evaluated*? (b) Why might this hold true even if the evaluator is a *stranger* and the evaluation *doesn't count* for anything?
** [hiddenAnswer]#(a) . (b) .#

. Why do people find it hard to *refuse a direct request*? If you were *designing an experiment* to assess circumstances under which people would refuse a request, how would you go about it?
** [hiddenAnswer]#Bar.#

. (a) Humans are a highly social species. What *social-cognitive abilities* might have been selected for in evolution to promote sociality? (b) Might there be any *drawbacks in modern culture* for some of these evolved abilities?
** [hiddenAnswer]#(a) . (b) .#