= Gambler's fallacy

* Also known as "Monte Carlo fallacy" (26 times black in a row in the Monte Carlo Casino in 1913) or "the fallacy of the maturity of chances".

.Definition
****
The belief that, if an event (whose occurrences are independent and identically distributed) has occurred less frequently than expected, it is more likely to happen again in the future (or vice versa).
****

* You said that 'runs' occur to statistically independent phenomena such as roulette wheel spins.
** This commonly believed fallacy can be said to have helped create an entire city in the desert of Nevada USA.
** Though the overall odds of a 'big run' happening may be low, each spin of the wheel is itself entirely independent of the last.
* When flipping a coin, subsequent throws have no impact to previous events, although we might think otherwise "to even things out".
** So after throwing (H=heads, T=tail) HHHHH, the next flip can be either H or T both with equal chances (and not T with higher chances, as most people would assume).
* Because: Future probabilities are NOT altered by past events.

== Example

"Red had come up six times in a row on the roulette wheel, so you knew that it was close to certain that black would be next up. Suffering an economic form of natural selection with this thinking, you soon lost all of your savings."

== Resources

* https://en.wikipedia.org/wiki/Gambler%27s_fallacy