= Hindsight Bias

.Definition
****
The tendency to exaggerate, after learning an outcome, one's ability to have foreseen the outcome.
****

* Also called the "I knew-it-all-along effect" or "creeping determinism".
* A general overconfidence in the certainty of one's judgments.
** Differently put: When people believe that an event is more predictable after it becomes known than it was before it became known.
** It's like watching a movie in reverse, and feeling smarter than the characters because we know what's coming.
* It contains three aspects:
.. memory distortion
.. beliefs about events' objective likelihoods, or
.. subjective beliefs about one's own prediction abilities.
* It is based on:
.. *Cognitive inputs*: People selectively recall information consistent with what they now know to be true and engage in sense-making to impose meaning on their own knowledge
.. *Metacognitive inputs*: The ease with which a past outcome is understood may be misattributed to its assumed prior likelihood
.. *Motivational inputs*: People have a need to see the world as orderly and predictable and to avoid being blamed for problems.

== Resources

* https://en.wikipedia.org/wiki/Hindsight_bias
