= Similarity-Attraction Effect

.Definition
****
We feel sympathy to others who are similar to ourselves (in important respects).
****

* As the English proverb states: "birds of a feather flock together" (and not opposites attracts!).
* We like which reminds us of ourselves: the same looks, thinking; even simply being from the same town.
** Liking, not in (romantic/physical) attraction, but more wanting to be around that person.
* Strongest for attitudes, values, activity preferences, and attractiveness; personality similarity has shown weaker, but still important, effects on attraction.
* Thus, sympathy is based on similarity; or differently put:
** Same stays with same.

== Explanation

* Similar people have usually similar opinions/worldviews, that validate our own; a source of social reinforcement.
* Anticipated rejection usually diminishes attraction, and with similar beings we expect less rejection.
* We enjoy it much with similar people due to shared interests/values/activity preferences.
* Pure chance, as our attitudes/values direct our behavior (calm people go to a meditation retreat, extroverted to a festival), and thus we are more likely to meet similar people.

== Resources

* https://psychology.iresearchnet.com/social-psychology/interpersonal-relationships/similarity-attraction-effect/