= Straw Man

Sometimes written as one word as in "strawman".

.Definition
****
Disproving an argument different from what's being discussed, while not acknowledging the distinction.
****

* In this informal fallacy, the typical straw man argument creates the illusion of having defeated an opponent's proposition.
** This is done through the hidden replacement of it with a different proposition ("stand up a straw man").
** And lastly through the subsequent refutation of that false argument ("knock down a straw man") instead of the opponent's proposition.
** You basically misrepresented (exaggerated, or completely fabricating) someone's argument to make it easier to attack (present own position as being reasonable).
* It's a strategy of the "dark side", as this kind of dishonesty serves to undermine honest rational debate.

== Example

After X said that we should put more money into health and education, Y responded by saying that he was surprised that X hates our country so much that he wants to leave it defenceless by cutting military spending.

== Resources

* https://en.wikipedia.org/wiki/Straw_man
