= Attitudes - Influencing thoughts and feelings

* Did you ever make a choice/acted a certain way precisely because someone said you should do the opposite?
* Due to the Industrial Revolution which lead to mass production, broader markets were available, and advertising was the natural result.
* In the 1880s, cigarettes were being mass-produced and aggressively advertised.
** Men bough 99% of all cigarettes sold, as it was considered socially unacceptable for a woman to smoke (otherwise they would have questionable morals).
** Ironically, somewhat later, smoking became a symbol of women's emancipation.
** The tobacco industry encouraged that view and started to target women in their advertisements.
** E.g. by claiming that cigarettes helped with weight control ("reach for a Lucky instead of a sweet").
* In 1955, 52% of men, and 34% of women in the US smoked.
** Fortunately, as of 2015, 21% men and 14% women smoke.
** Tobacco companies begun aggressive marketing in other countries.
*** Smoking may kill one-quarter of the young people currently living in Asia.
* Question being: Is advertising responsible for shaping people's attitudes/behaviors?

== Nature and Origin

* What types of attitudes do exist, and what are they based on?
* We all evaluate the world around us. We form likes and dislikes.
** It would be odd to hear something like: "I feel completely neutral toward anchovies, chocolate, Mark Rutte, and Donald Trump".
* Attitudes = Evaluations of people/objects/ideas.
** They are important to determine what we do (eat, avoid, download, vote for).

=== Where come from?

* In part the come from our *genes*.
** Identical twins share more than do fraternal; even when raised apart and never knew each other.
** Temperament/personality directly related to genes; predisposing us to certain dis-/likings.
* *Social experiences* also shape our attitudes. Three *components*, to be precise:
.. Cognitive: thoughts and beliefs about the attitude object.
.. Affective: emotional reactions toward it.
.. Behavioral: how we act toward it.

==== Cognitively Based Attitudes

* Our evaluation is based on relevant facts to form a belief about the property of an object.

.Cognitively Based Attitudes
****
An attitude based on beliefs (about an attitude object's properties).
****

* E.g. to buy or not to buy a vacuum cleaner?
** We weigh the pros and cons, whether we want to have it or not.
** Relevant criteria like how well it can clean up the dirt, and how much it costs.
** No emotional considerations, such as how sexy it makes us feel.

==== Affectively Based Attitudes

* When an attitude is rooted in emotions and values, instead of objective appraisals.

.Affectively Based Attitudes
****
An attitude based on feelings/values (instead of beliefs) about the nature of an attitude object.
****

* We sometimes feel very attracted to something (or someone,) although we might have negative beliefs about it/him/her.
* Usually topics which are considered inappropriate to be talked about at a dinner table are likely to be affectively based:
** Politics, sex, and religion.
* We also vote more out of affection ("he looks caring") than our beliefs about the specific policies.
* Where do they come from?
** Our values, basic religious/moral beliefs.
*** E.g. abortion, death penalty, premarital sex, gay marriage; based on sense of value than cold examination of facts.
*** Function is less to draw an accurate picture, but more to validate one's basic value system.
** Or from a sensory reaction:
*** Such as liking the taste of a certain food.
*** An aesthetic reaction, such as admiring a painting or shape/color of a car.
** Or simply conditioning.

.Classical Conditioning
****
A stimulus is given, creating an emotional response, and then paired with a neutral stimulus, until it takes on the emotional properties of the first stimulus.
****

* Classical conditioning (also called Pavlovian Conditioning) works this way:
** A stimulus (US=Unconditioned Stimulus) is presented eliciting an emotional response (UR=Unconditioned Response).
** With this US, a neutral stimulus (CS=Conditioned Stimulus) is presented at the same time, which originally elicits no emotional response.
** After a while (being exposed to both stimuli), the CS itself is able to evoke an emotion response (CR=Conditioned Response).
* Example:
** A dog is presented with food (US) and produces saliva (UR).
** Along with presenting food, a bell is rung (CS).
** After a while, the sound of the bell itself will be able to create saliva production (CR).

.Operant Conditioning
****
Freely chosen behavior becomes more/less frequent based on reward/punishment.
****

* Rewards (also called positive reinforcements) can change our attitudes due to changed associations.
* Affectively based attitudes come from many sources, still they can be grouped into one category, because they:
.. don't result from a rational examination.
.. aren't governed by logic.
.. are often linked to people's value.

[NOTE.tryit,caption=TRY IT]
====
*Measure affective vs cognitive bases of attitudes*

*Question 1*: Circle the number which best describes _your feelings_ toward snakes.

[%autowidth,cols="1,0,0,0,0,0,0,0,1"]
|===
|hateful|-3|-2|-1|0|+1|+2|+3|love
|sad|-3|-2|-1|0|+1|+2|+3|delighted
|annoyed|-3|-2|-1|0|+1|+2|+3|happy
|tense|-3|-2|-1|0|+1|+2|+3|calm
|bored|-3|-2|-1|0|+1|+2|+3|excited
|angry|-3|-2|-1|0|+1|+2|+3|relaxed
|disgusted|-3|-2|-1|0|+1|+2|+3|acceptance
|sorrowful|-3|-2|-1|0|+1|+2|+3|joy
|===

*Question 2*: Circle the number which best describes the _traits/characteristics_ of snakes.

[%autowidth,cols="1,0,0,0,0,0,0,0,1"]
|===
|useless|-3|-2|-1|0|+1|+2|+3|useful
|foolish|-3|-2|-1|0|+1|+2|+3|wise
|unsafe|-3|-2|-1|0|+1|+2|+3|safe
|harmful|-3|-2|-1|0|+1|+2|+3|beneficial
|worthless|-3|-2|-1|0|+1|+2|+3|valuable
|imperfect|-3|-2|-1|0|+1|+2|+3|perfect
|unhealthy|-3|-2|-1|0|+1|+2|+3|wholesome
|===

Add up the sum of both questions separately. Question 1 measures the affective, and 2 the cognitive component of attitude towards snakes. For more affectively based attitudes, the first question departs more from zero (usually negative). If you'd replace snake with vacuum cleaner, the first one would be more zero and the second one depart more from it, as it as a pure utilitarian object.
====

==== Behavioral Based Attitudes

.Behavioral Based Attitudes
****
Attitudes based on observations of how one behaves toward an object.
****

* How we observe our own behavior, which seems odd.
** How do we know how to behave, if we don't already know how we feel?
** *Self-perception theory* states: We don't know how we feel until we see how we behave.
** Thus, justifications like: "_I guess I like it, because I always seem to be going for it._"
* We infer our attitudes only if: 1) our initial attitude is weak/ambiguous and 2) no other plausible explanation is available.
** If you exercise to lose weight (or your doctor said so), you will unlikely think you truly enjoy it.

=== Explicit vs. Implicit Attitudes

* Once an attitude develops, it can be either explicit (conscious) or implicit (involuntary, uncontrollable).
** When we ask someone about their opinion, they can only report about their explicit attitudes.
* When people review job applications, when the name of the applicant sounds familiar to a member of their own race (George, Greg) they are more likely to accept them than if they sound from another group (Jamal, Lakisha).
** Although people would never admit that, not even being consciously aware of it, it still happens.
** Those negative feelings are triggered automatically because of the negative implicit attitude.

.Explicit Attitudes
****
We consciously endorse and can report on them.
****

.Implicit Attitudes
****
Existing outside conscious awareness.
****

* We can have implicit attitudes toward virtually anything, even math.
* To measure it, there is an IAT (Implicit Association Test).
** E.g.: https://implicit.harvard.edu/implicit/selectatest.html
* Implicit attitudes are more rooted in our childhood experiences, whereas explicit ones are more in recent experiences.
** When it comes to overweight people, when we had a good relationship with our mother, and she was overweight, we had a positive implicit attitude, even if our explicit attitudes were negative.
* This field is still young and heavily being researched.
* See chapter 13 where we will apply this to stereotyping and prejudice.

[NOTE.test,caption=REVIEW QUESTIONS]
====
link:test.html#test1[Test yourself]
====

== Attitudes Predicting Behaviors

* What are the conditions under which attitudes can predict behavior?
* Why are companies willing to spend so much money on advertising?
** Because when we change our attitudes, we also change our behavior (e.g. cigarettes are for women too).
* Study of 1930 by LaPiere:
** On a sightseeing tour with a Chinese couple, he expected to experience prejudice.
** But surprisingly only 1 of 251 establishments refused service.
** To check the attitudes again, he wrote a letter asking whether they would serve a Chinese visitor.
*** Only 1 said yes, 90% no, the rest was undecided.
** So it seems that there is a big lack of correspondence between our attitudes and the way we actually act.
** Yet, the relationship between attitude and behavior is way more complex than this study shows...
* Attitudes do indeed predict behavior, but only under certain specifiable conditions.
** E.g. Knowing whether the behavior we are trying to predict is spontaneous or planned.

=== Spontaneous

* How to predict spontaneous behavior?
* We act spontaneously when we think little about what we are about to do.
** Making a snap decision for example when a Chinese couple enters our restaurant.
* Attitudes will predict spontaneous behavior only when they are highly accessible to us.

.Attitude Accessibility
****
Association strength between attitude object and one's evaluation of that object, measured by report speed how they feel about it.
****

* So it's about how quick we can evaluate our attitude towards an object.
** If it's low, our attitude come to mind slower.
** If it's high, that attitude will more likely predict spontaneous behavior.
* But what makes attitudes accessible in the first place?
** The degree of experience we have behaving with the attitude object.
** E.g. hands-on experience; volunteering for at a homeless shelter, affecting attitude towards the homeless.
*** Compare this with a person who only reads about homeless people in the newspaper - not very direct, not very accessible.

=== Deliberative

* Now what about predicting deliberate behavior?
* When we are motivated, take our time and make deliberate choices?
** Even inaccessible attitudes can bubble up and influence the choice we make.
* The best-known theory of when/how attitudes predict deliberative behavior is the theory of planned behavior.

.Theory of Planned Behavior
****
Our intentions are the best predictors of deliberate behavior; determined by attitudes toward specific behaviors/subjective norms/perceived behavioral control.
****

* Although some behaviors come from spontaneous decisions, others are based on thoughtful processes, weighing pros and cons.
* When we have time to contemplate, the best predictor is our intention.
* Intention is determined by:
.. attitude toward the behavior: our specific, not general attitude toward that behavior
.. social/subjective norms: our beliefs about how others will judge that behavior
.. perceived behavioral control: the ease how we think we can perform that behavior

==== Specific Attitudes

* The more specific the attitude, the easier to predict the behavior.
* LaPiere might have asked the wrong question.
** If he had asked whether restaurant owner would serve "a well-dressed Chinese couple accompanied by a White American college professor", their answer would have been more predictive of their actual behavior.
** Instead, he simply asked whether they would serve "members of the Chinese race".

[%autowidth,cols="1,0"]
|===
|*Attitude Measure*|*Correlation*
|Birth control|0.08
|Birth control pills|0.32
|Using birth control pills|0.53
|Using birth control pills during the next 2 years|0.57
|===

* This table clearly shows that when being asked more specific questions, the answer are a better predictor for the actual (correlated) behavior.

==== Subjective Norms

* Our beliefs, how others (which we care about) will view that behavior.
* Imagine you don't like classical music but your best friend is playing in a concert.
** You assume that she will be disappointed if you don't go; fail to show up would be like a slap in the face.
** Knowing this subjective norm (how she will view your behavior), we might predict that you will go nevertheless.

==== Perceived Behavioral Control

* How easy we think it will be for us to perform that behavior.
* If we think it will be difficult, we will not form a strong intention to do so.
** Like remembering to use a condom when having sex.

[NOTE.tryit,caption=TRY IT]
====
*Predicting environmentally friendly action*

* Many of us hold environmental friendly beliefs...
** most recyclable waste is not recycled.
** few use energy efficient light bulbs.
** many drive alone to work with their car.
* One useful predictor for environmental friendly behavior is how we feel about a prototypical environmentalist.
** The mental image that pops up when being asked to think of the average environmentalist.
* Rate that person (and many others like professors, bicyclists) how attractive, cool, fun, intelligent, and judgemental they are; without time limit.
** These ratings assess the _explicit_ attitudes about environmentalists.
* Then again rated a category (such as environmentalist), but now under extreme time pressure (less than a second).
** Because very little time to think / control their responses, this measures the _implicit_ attitudes.
* Finally, participants were asked about their environmental friendly behavior (low thermostat, reusable bags, short showers).
* Confirmation: The more positive the image, the more likely to engage in pro-environmental behaviors.
** This is true for explicit as well as implicit attitudes.
* Conclusion: Don't ask whether someone considers themselves as a XYZ, but rather how they feel about the _average_ XYZ.
====

[NOTE.test,caption=REVIEW QUESTIONS]
====
link:test.html#test2[Test yourself]
====

== How to Change

* How can internal/external factors lead to attitude change?
* They do so often in response to social influence (what others do/say).
** It can be actual or even imagined behavior of others
** The base of advertising: your attitudes toward a product can be influenced by publicity.

=== Cognitive Dissonance

* Changing attitudes by changing behavior.
* We know that we change our attitude, if we behave inconsistently to them, and we can't find external justification.
** This cognitive dissonance appears when something threatens our self-image (as decent, kind, honest).
** Especially if there is no way to explain away this behavior based on external circumstances.
* If you want to change someone's attitudes, make _them_ give a speech for/against whatever it is.
** For that, they then need to find internal justification, to reduce their experienced dissonance.
** By that, you get them believe what they are saying.
* Is this also possible to carry out on a mass scale? Difficult...

.Persuasive Communication
****
A message advocating a particular side of an issue.
****

=== Persuasive Communication

* If you run a campaign about cancer, should you...
** ... provide lots of facts and figures?
** ... provide emotionally loaded, frightening visual images of diseased lungs?
** ... hire a movie star/Nobel Prize-winning medical researcher?
** ... take a friendly tone, acknowledging quit smoking is hard, or take a hard line?
* It's complicated; luckily researchers at Yale University conducted studies to figure out what makes persuasive communication effective ("Who says what to whom"):
.. Who - Source of communication
*** Speaker's credibility: judging his expertise
*** Speaker's attractiveness: physical or personality attributes
*** Sleeper effect: low-credibility sources becomes more persuasive with passage of time; as we remember the message itself longer, than information about its source
.. What - Nature of communication
*** more persuasive if message seem not to be designed to influence (manipulate); also of course the quality of arguments themselves
*** both sides are being presented (for and against); two-sided communication
*** order effects when there are multiple speeches: if there is no break in-between better give the first speech as more persuasive (primacy effect); if there is a delay where people will make up their minds better be the last (recency effect)
.. To Whom - Nature of audience
*** if it is more distracted, more likely to be persuaded
*** is it hostile or friendly to the point of view
*** individual differences: lower intelligence, moderate self-esteem, age 18-25
*** cultural differences: Western value personal preferences ("I like it because it makes me feel good"-message); Eastern more contextually appropriate behavior ("I like it because others I am connected to like it"-message)

.Yale Attitude Change Approach
****
Which conditions people most likely to change their attitudes, in response to persuasive messages. Focusing on the source and nature of communication, and nature of the audience.
****

==== Central/Peripheral Routes to Persuasion

* When is it better to focus on aspects which are:
.. central to the communication (argument strength)
.. peripheral to it (credibility/attractiveness of the speaker)
* This question is answered by the elaboration likelihood model.
** When we are influenced by the speech (argument logic) and when by superficial things (who give the speech, how long is it).

.Elaboration Likelihood Model
****
Persuasive communication can change attitude either centrally (listeners motivated, pay attention to arguments) or peripherally (no attention to arguments, but superficial things).
****

* Sometimes we are motivated to pay attention to the facts.
** Think carefully about the content, the logic of the arguments, elaborate on the message.

.Central Route to Persuasion
****
When we have the ability and the motivation to elaborate; listening carefully, thinking about the arguments.
****

* When we don't pay close attention to what is being said, we stay with surface characteristics.
** E.g. how long or by whom (expert or not, attractive) is the speech given.
** Meaning, things which are peripheral to the message itself.
* This is why companies pay celebrities lots of money to represent (ads, tweets, posts, product placements) their brands.

.Peripheral Route to Persuasion
****
When we don't elaborate on the arguments; instead focus on superficial things.
****

* What determines which route we are taking?
** This depends on whether we
... have the ability (nothing is distracting us) and
... motivation (it's fascinating to us) to pay attention.
* Effects on attitude change:
** Central route is long-lasting and resistant to change.
** Peripheral route is temporary and susceptible to change.

==== Motivation to pay attention

* If it is relevant for us personally, then we are motivated to pay attention to a communication and its arguments.
** E.g. how important the topic is to our well-being.
* More relevant, more willing, more likely taking the central route to persuasion.
** When being presented a relevant topic, you will agree more when there are strong arguments than weak (regardless of who presents it).
** Of course, when it's not relevant, not arguments but the speaker/speech is more influential (peripheral route).

==== Ability to pay attention

* Even when we sometimes _want_ to pay attention, we can't.
** We are tired, sitting in a hot or crowded room... the issue is too complex/hard to evaluate.
* In that case, we are swayed more by peripheral cues.
* If the arguments are too complicated, conveyed in jargon, we rely on the expert's credentials
** If we are able to understand the arguments, we engage in a central route.
* Our expertise/personal tendencies shape our ability to pay attention to persuasive arguments.
** Also: "Morning" people will take the central route more likely when persuasion is earlier in the day (vice versa for "evening" people).

==== Achieving long-lasting attitude change

* When basing our attitudes on careful analysis of arguments, we are more likely to maintain an attitude over time.
* Also, more likely to behave consistently with it, and more resistant to counter-persuasion.

=== Emotion

* Before an argument can be even considered, we need a person's attention.
** One way to do this is by playing to their emotions.

==== Fear-Arousing Communications

* One easy way is to scare them (showing diseased lungs), presenting alarming data (linking smoking with lung cancer).

.Fear-Arousing Communications
****
Persuasive messages changing attitudes by arousing fears.
****

* Public service ads often use this approach.
** Scare people into: safer sex, wearing seat belts, lower carbon emissions, and stay away from drugs.
* Whether it works or not depends...
** Moderate fear, and message will reduce that fear, more likely go via the central route.
* E.g. watching videos of lung cancer, and reading flyers about how to quit smoking, people significantly stopped more compared to people who only got one of the two.
** Why is that? Because the video evoked fear, and the flyer reduced it again by following its instructions.
* It will fail if the fear is so strong that people feel overwhelmed.
** People will become defensive; deny the importance of the threat; unable to think rationally.
* So the goal is to create enough fear to motivate, but not so much so people will tune out.
** Make sure to include some specific recommendations, making it clear that this will reduce their fear.

==== Emotions as Heuristic

.Heuristic-Systematic Model of Persuasion
****
Persuasive communication changes attitudes because of A) systematically processing arguments or B) using mental shortcuts/heuristics.
****

* When we use the peripheral route, we often use heuristics (=mental shortcuts)
** Making judgements quickly/efficiently; no need to spend a lot of time analyzing every detail.
** For example "_experts are always right_" and "_people who speak quickly must know what they're talking about_".
* Emotions can also be used as heuristics, to determine our attitudes: The "how do I feel about it"-heuristic.
** If we feel good about it, we must have a positive attitude. Most of the time this actually works.
* Sometimes though it's difficult to tell where our feelings come from.
** Is it really that thing at hand, or something totally unrelated?
** Maybe you were in a good mood to begin with; maybe the store played your favorite song?
** When we mistake what caused our mood, we misattribute feelings created by one source (favorite song) to another (the product) we bought.
* That's why salespeople play music and put art in their stores; real estate agents bake cookies.
** They hope that at least a bit, those pleasant feelings will be partly attributed to the product being sold.
* Generally speaking: Emotions can influence the way we think about persuasive messages.
** When in a good mood, we relax, assuming the world is a safe place; being more content with heuristic cues ("the expert says").
** When in a bad mood, we are more alert, skeptical, and thus pay more attention to message quality.
** We are easily persuaded by a weak message when we're happy, it takes a strong message when we're sad.

==== Emotion and different types of attitudes

* Success also depends on the type of attitude we try to change.
** Whether they are cognitively (object itself) or affectively (emotions/values) based attitudes.
* It's best to fight fire with fire: Cognitively based = rational arguments; affectively = emotional appeals.
** For utilitarian products (air conditioner, vacuum cleaner), we focus on functional aspects.
** For social identity products (perfume, greeting cards), we focus on other's perception/judgement.

=== The Body

* Body posture plays a surprising role in the process of attitude change.
** Study with people testing the durability of new headphones, while hearing some arguments (behavioral change:
** Shaking head ("no"): less confidence
** Nodding head ("yes"): more confidence
*** ... about our thoughts about the message:
**** "Wow, this is really convincing" - for strong argument
**** "Wow, this is really dumb" - for weak arguments
* Thus: What people do while you try to convince them matters.
** Sitting in a soft, cushy chair at the store: spend more money than planned.
** Make customers smile to transfer positive feelings towards the product
*** Increase customer's confidence in their thoughts about your message (more effective).
*** But only if the argument is strong and convincing in the first place.

[NOTE.test,caption=REVIEW QUESTIONS]
====
link:test.html#test3[Test yourself]
====

== Power of Advertising

* Advertising is a direct application of social psychology.
** To change how customers think about/act toward a certain product.
* Advertising _is_ powerful; people are surprisingly susceptible to its influence.
** Yet, everyone thinks it works on everyone else but themselves.
* Powerful tools such as: advertising, product placement, and behavior of admired figures.

=== How it works

* How does it work (best)?
** Same as already discussed before!
* Change an affectively based attitude => fight emotions with emotions.
* E.g. brands of cola are not really that different.
** We don't evaluate them based on objective qualities; ads don't stress facts and figures.
** "The thing about soda commercials is that they actually have nothing to say."
** Instead, they try us to associate feelings of excitement/youth/energy/attractiveness with the brand.
* Advertising is even harder for products which neither trigger emotions nor are directly relevant for daily life.
** Solution/trick: _Make_ the product relevant for them.
** E.g. Listerine: how to treat throat infections.
** No one used mouthwash, or even knew what one was.
** They have invented the cure, now they invented the disease.
* Playing with people's fears being socially rejected.
** Making a problem (bad breath) which is personally relevant for the masses.
* See: https://www.youtube.com/watch?v=kzAbNH9-2eU

=== Subliminal Advertising

* A form of mind control?
* What happens if we are not even aware that someone tries to persuade us?

.Subliminal Messages
****
Words/pictures not consciously perceived, but may influence nevertheless judgements/attitudes/behaviors.
****

* Ads sometimes contain the word sex, or show hidden images of male and female genitalia (see books from link:https://en.wikipedia.org/wiki/Wilson_Bryan_Key[Wilson Bryan Key]).
** Although not being consciously perceived, people in a good mood while pay longer attention to them.
* They can be visually, but also auditory: Think of all the subliminal audio clips on YouTube.
** There is a large market with those clips, for weight loss, stop smoking, raise self-esteem...
* Most people believe those messages actually do work, and shape their attitudes and behaviors -but do they?

==== Debunking

* There is no evidence that subliminal messages have an influence on our behavior.
* Hidden messages don't make us buy stuff, any more we normally would do.
* Thus, unfortunately, those audio clips won't help us to quit smoking or lose weight.

==== Laboratory evidence

* Subliminal messages don't work in _everyday life_.
** Yet, under very specific, laboratory controlled, circumstances they do!
* People were shown subliminal flashes of the words "Lipton Ice".
** If they were not thirsty, it had no effect.
** If they were thirsty, they were significantly more likely to choose that beverage.
* For subliminal messages to work:
.. The illumination of the room must be right.
.. People seated the right distance from the screen.
.. Nothing else is occurring to distract them.
* Warning people that someone is going to persuade them, decreases the potential influence.

[NOTE.tryit,caption=TRY IT]
====
*Consumer Brand Attitudes*

Two exercises on automatic thought about consumer-related attitudes.

. Baseline memory assessment.
** Read those four word-pairs loud.
** Your partner has to remember them later.
... blue-duck
... ocean-moon
... window-hammer
... ski-climb
** While your partner is rehearsing them, read the following questions and ask for immediate, first-instinct responses:
... Name an automobile brand
... Name a laundry detergent brand.
... Name a soft drink brand.
** The word pairs most likely primed your partner to say "Tide" and "Mountain Dew" (if you live in the US), and there was actually no memory test.
** Priming makes certain thoughts/concepts/attitudes more accessible.
. Consider the following 8 companies: Which are the top 3 in terms of revenue:
** Berkshire Hathaway, McKesson, Cardinal Health, Boeing, Microsoft, Target, Coca-Cola, American Express, Starbucks.
** Fun fact: The list is already in the right order.
** You may never have heard about the first ones, still chose others.
** link:../../phenomena/availability_bias.html[Availability bias]: what comes more easily to mind/more popular/successful.
** Advertising pays off in the long run.
*** We tend to think pleasant thoughts about which is familiar (link:../../phenomena/mere_exposure_effect.html[mere exposure effect]).
====

=== Culture

* Media messages are most powerful, when people consciously perceive them.
* Media also shapes/reflects cultural attitudes.
** Attitudes towards women/men, races, ages, ...
** Related how they are portrayed in advertising (TV, movies, internet).
* Western stress independence/individualism, Eastern stress interdependence/collectivism.
** These differences (along with advertisement) predict attitudes.
** Independence: "It's easy when you have the right shoes", interdependence: "the shoes for your family".
** Ads in US: individuality/self-improvement/individual benefits; ads in Korea: family/others/social group benefits.

[NOTE.test,caption=REVIEW QUESTIONS]
====
link:test.html#test4[Test yourself]
====

== Resisting Persuasive Messages

* Strategies to resist efforts at persuasion.
** How can we be safe from persuasive communications? Counter-strategies?!

=== Inoculation

* Like medical inoculation (vaccination): Exposed small amount, weakened virus; become more resistant.
* Considering the other's arguments before he attacks: Think about pro/cond beforehand.
** Thinking ahead of time, about various directions of a counter-argument.
* Less susceptible to efforts to change your existing attitude.

.Attitude Inoculation
****
Immune to attempts to change attitudes, by exposing to small dose of counter-arguments.
****

=== Product Placement

* Heineken paid 45 million dollars to be placed in a James Bond movie (to drink beer, instead Martini).
** What about the Lego movie: where does product placement end and the film begin?
* Works, because we don't realize that someone tries to influence our attitudes/behaviors; defenses are down.
** We don't generate counter-arguments.
* Children are especially vulnerable.
** When they saw movies where people smoked, they smoked later as well.
* Is warning people beforehand an effective tool? Yes!
** People are less susceptible when forewarned; analyze and hear more carefully.

=== Peer Pressure

* Many efforts, trying to change our attitudes, contain appeals to our *emotions*.
* Adolescents (very susceptible age) start with smoke/drink/drugs because of peer pressure.
** Best predictor whether someone starts with it, whether that person has friends doing it.
** Peer pressure is linked to our values/emotions, fear of rejection, desire for freedom/anatomy.
** In adolescents, peers are an important source of social approval.
* Using inoculation (doses of logical arguments one might hear) to prevent young people from smoking.
** Making them immune from social pressure by exposing to mild versions of it.
** Showing ways how to combat these pressures, via a role-play for example: calling him a "loser".
** "_I'd be more of a loser if I did it just to impress you._"

=== Reactance Theory

* When persuasion attempts backfire.
** There is harm for strong prohibitions, which is it that it increases the interest in the prohibited activity.
** We simply don't like it when (we feel) our freedom is threatened.
** It leads to an unpleasant state of reactance, which can be reduced by performing the threatened behavior.

.Reactance Theory
****
When our freedom is threatened, resistance arises, and reducing it by doing the forbidden.
****

* Doing something just because an authority told you not to do it? That's reactance.
** When stating "Don't write on this wall" versus "Please don't write on this wall", then the first one will have more graffiti.
** The behavior will restore the sense of personal freedom/choice.
* We are not automatons, that must march blindly.
** Sometimes it's worth the cognitive effort, in order to avoid being influenced.

[NOTE.test,caption=REVIEW QUESTIONS]
====
link:test.html#test5[Test yourself]
====

== Summary

* Types of attitudes and what based on
** Nature and origin of an attitude: it's our enduring evaluation of people/objects/ideas
** Come from
*** mostly experiences (a bit of genetics)
*** Cognitively based: our beliefs
*** Affectively based: emotions and values (created by classical/operant conditioning)
*** Behaviorally based: on actions
** Explicit vs Implicit
*** consciously endorse, easily report VS outside conscious awareness
* Conditions where attitudes predict behavior
** Spontaneous behaviors
*** Relatively accessible
*** Attitude accessibility: association strength between object and its evaluation
** Deliberative behaviors
*** Theory of planned behavior: we deliberately behave because 1) attitudes towards it 2) subjective norms 3) believe have control our behavior
* Internal/external factors lead to attitude change
** Change attitudes by change behavior: Cognitive dissonance theory
*** Counter-attitudinal advocacy for low external justification
*** Attitudes in line with behavior
** Persuasive communications
*** Effectiveness depends on 1) source of message 2) message itself 3) audience
*** Elaboration likelihood model: when more persuaded by arguments, when by surface characteristics (e.g. attractiveness of speaker)
*** Central route to persuasion: when have motivation/ability to pay attention
*** Peripheral route to persuasion: low motivation/ability
** Emotion
*** Fear-arousing communication: lasting attitude change (if moderate)
*** Believe reassured by the message
*** Using emotions as heuristics to gauge attitude: feel good near it, infer we like it (even if caused by something else)
*** Effectiveness depends on type of attitude: Appeals to emotion/social identity work best, if attitude based on emotions/social identity.
* Advertising
** Effective changing attitudes (especially in public health campaigns)
** How it works?
*** Targeting affectively based attitudes: play with emotions
*** Targeting cognitively based attitudes: show facts, make product seem personally relevant
** Subliminal advertising
*** A form of mind control? No!
*** No evidence that subliminal messages have any influence
*** They DO have influence under controlled laboratory conditions
** Culture
*** Differences that converge with other cross-cultural findings in social and self-perception
* Strategies resisting persuasion
** Attitude inoculation
*** Expose small doses of arguments against their position
*** Easier to defend later on (like vaccination)
** Product placement
*** When warned before, less susceptible
** Peer pressure
*** Teach how to resist it, makes kids less vulnerable to it
** Reactance theory
*** When freedom threatened, feel like choices are limited; it backfires!

[NOTE.test,caption=REVIEW QUESTIONS]
====
link:test.html#test6[Test yourself]
====