= Lecture Introduction

== Overview

How does human behavior come about?
What is the role of the brain?
How are we through evolution, development and learning adapted to our environment, so that we can function and grow?
What is consciousness?
How are our emotions expressed?
How do we behave towards others?
These are just a few of the fascinating questions that are central to psychology.

Answering these question has, in addition to the acquired knowledge, also practical use.
The knowledge enables the psychologist to analyse what is going wrong with people which have difficulties in life or don't function properly in their environment, so that professionally a positive change can be made.

The question, what psychology actually is, will be answered very broad.
You will get an overview over the complete domain of psychology, so that you have a solid foundation for the education of psychology.

Generally speaking studies psychology the behavior, emotions and thoughts of humans, in relation to oneself and in relation the body, as well as the social environment.
This course has a particular focus on the ability to adapt of humans.

The course offers a solid, yet accessible basis in the field of evolutionary psychology and theoretical principles with which the capabilities for adaption can be understood.

We then study how the brain is organized, how we perceive sensations and how we experience our self and the world around us.
How we think, reason, solve problems and decide.
You will get insight in our drives and emotions that give shape to our behavior.
Of course these actions always happen in a social context.
People behave differently when they are in a group compared to when they are alone.
People influence each other, consciously or not.
In addition, human behavior changes over the life.
Finally the course will cover psychological disorders and treatments of those.

See: link:https://mijn.ou.nl/group/ou/studieaanbod#!speoproduct/PB0014/BPS/2021-2022[MijnOU]

== Objectives

After this course you are able to:

. Recognize and name three fundamental insights into the history of psychology that underlie contemporary psychology.
. Recognize sub-disciplines in psychology and know what they are about and which methods they use for examination.
. Recognize and name the research designs, methods and techniques of data collection/processing.
. Describe how the environment affects human behavior through both natural selection and experience.
. Recognize/name basic concepts, theories, research results within biological psychology, and how behavior is established at a neural/hormonal level.
. Recognize/describe sensory/perceptual mechanisms and how these mechanisms contribute to the survival of the species from a functional perspective.
. Recognize/name different memory systems and their adaptive functions, as well as cognitive processes underlying our problem-solving abilities.
. Recognize/name the basic concepts, the most important theories and research results within developmental psychology, social psychology and personality psychology.
. Recognize/name the characteristics and presumed mechanisms of the main mental disorders and the rationale and characteristics of some commonly used treatment approaches.
. Identify the domains in which psychologists work, where psychological knowledge is relevant and what the main values, activities and methods used are of health care psychologists, life course psychologists, clinical psychologists and industrial psychologists.

See: link:https://youlearn.ou.nl/web/pb0014212212/leerdoelen[Leerdoelen]