= Focus Questions

. How is psychological disorder defined by American Psychiatric Association? What ambiguities lie in that definition?
** [hiddenAnswer]#Bar.#

. How does validity differ from reliability? How can the validity of the DSM be improved through further research and revisions?
** [hiddenAnswer]#Bar.#

. What are some negative consequences of labelling a person as psychologically disordered? What is recommended as a partial solution to this problem?
** [hiddenAnswer]#Bar.#

. How does the example of homosexuality illustrate the role of culture in determining what is or is not a “disorder”?
** [hiddenAnswer]#Bar.#

. How is ADHD identified and treated? How do critics of the high rate of diagnosis of ADHD explain the high rates?
** [hiddenAnswer]#Bar.#

. How are Down syndrome and Alzheimer’s disease characterised as brain diseases?
** [hiddenAnswer]#Bar.#

. How can the causes of psychological disorders be categorised into three types – “the three Ps”?
** [hiddenAnswer]#Bar.#

. What are four possible ways of explaining sex differences in the prevalence of specificpsychological disorders?
** [hiddenAnswer]#Bar.#

.  How can generalized anxiety disorder be understood in terms of hypervigilance, genes, early traumatic experiences, and cultural conditions?
** [hiddenAnswer]#Bar.#

. What evidence links phobias to the kinds of fears that most people have?
** [hiddenAnswer]#Bar.#

. How might phobias be explained in terms of learning that has been prepared by evolution?
** [hiddenAnswer]#Bar.#

. Are phobias such as fear of snakes “innate”? Can an evolutionary perspective help us explain some phobias?
** [hiddenAnswer]#Bar.#

. What learned pattern of thought might be a perpetuating cause of panic disorder?
** [hiddenAnswer]#Bar.#

. How are obsessive-compulsive disorders similar to phobias? How do they differ? What kinds of obsessions and compulsions are most common?
** [hiddenAnswer]#Bar.#

. How might damage to certain areas of the brain result in obsessive-compulsive disorder?
** [hiddenAnswer]#Bar.#

. How does posttraumatic stress disorder differ from other anxiety disorders?
** [hiddenAnswer]#Bar.#

.  What conditions are particularly conducive to development of posttraumatic stress disorder?
** [hiddenAnswer]#Bar.#

. Why might some people be more susceptible to PTSD than other people?
** [hiddenAnswer]#Bar.#

. What are some similarities and differences between depression and generalized anxiety?
** [hiddenAnswer]#Bar.#

. According to the hopelessness theory, what pattern of thinking predisposes a person for depression? What is some evidence for that theory?
** [hiddenAnswer]#Bar.#

. How might rumination serve to enhance or worsen depression?
** [hiddenAnswer]#Bar.#

. How did Kendler demonstrate that the onset of major depression typically requires both genetic predisposition and a severely stressful life event?
** [hiddenAnswer]#Bar.#

. What early evidence supported the theory that depression results from a deficit in the neurotransmitters norepinephrine and serotonin? Why is that theory now doubted?
** [hiddenAnswer]#Bar.#

. According to a new theory, how might stressful experiences alter the brain in a way that brings on depression?
** [hiddenAnswer]#Bar.#

. How might moderate depression, following a loss, be adaptive?
** [hiddenAnswer]#Bar.#

. According to Keller and Nesse, how might depressed moods vary, adaptively, depending on the situation?
** [hiddenAnswer]#Bar.#

. How are manic states experienced? What is some evidence linking mild manic (hypomanic) episodes to heightened creativity?
** [hiddenAnswer]#Bar.#

. What’s the evidence that creativity is related to hypomania?
** [hiddenAnswer]#Bar.#

. What are the five main classes of symptoms of schizophrenia?
** [hiddenAnswer]#Bar.#

. What early evidence supported the dopamine theory of schizophrenia? Why is the simple form of that doubted today?
** [hiddenAnswer]#Bar.#

. What evidence supports the theory that a defect in glutamate neurotransmission may play a role in schizophrenia?
** [hiddenAnswer]#Bar.#

. How might an exaggeration of a normal developmental change at adolescence help bring on schizophrenia?
** [hiddenAnswer]#Bar.#

. How do the varying rates of concordance for schizophrenia among different classes of relatives support the idea that heredity influences one’s susceptibility for the disorder?
** [hiddenAnswer]#Bar.#

. What sorts of early disruptions to brain development have been implicated as predisposing causes of schizophrenia?
** [hiddenAnswer]#Bar.#

. What evidence suggests that the family environment may promote schizophrenia, but only in those who are genetically predisposed for the disorder?
** [hiddenAnswer]#Bar.#

. What cross-cultural difference has been observed in rate of recovery from schizophrenia? What are some possible explanations of that difference?
** [hiddenAnswer]#Bar.#

. What is a personality disorder, and how is it similar to and different form related, more serious disorders?
** [hiddenAnswer]#Bar.#

. Describe the three clusters of personality disorders. Within each cluster, how easy do you think it is to differentiate the symptoms of one disorder from those of others?

== Think Critically

. Foo
** [hiddenAnswer]#Bar.#

. Foo
** [hiddenAnswer]#Bar.#

. Foo
** [hiddenAnswer]#Bar.#