= Focus Questions

. What are the three *phases of prenatal development* and what are the major milestones of each phase?
** [hiddenAnswer]#1) Zygotic (germinal): Sperm fertilizes the egg, travels to uterus for two weeks, implanting to uterine wall. 2) Embryonic: Week 3-8, major organ systems develop. 3) Fetal: Week 9+ (about 38 weeks), growth/refinement of organs/body structure.#

. When is the unborn child most susceptible to the effects of *teratogens* and why?
** [hiddenAnswer]#During embryonic, preventing an organ (kidney, hands, feet) from developing properly, as most differentiation is happening here (drastic effect!).#

. How might *prenatal experience* "prepare" a fetus for postnatal life?
** [hiddenAnswer]#Those experiences can be used as a "forecast" of the future environmental condition. E.g. when pregnant women have poor diets, they give birth to "thrifty phenotypes", babies who store fat more easily. Or when mothers are exposed to stress, babies will more likely be anxious/fearful/impulsive/reduced executive functions/etc. Not all can be seen as bad, e.g. aggression/risk taking could be a preparation for the (hostile) environment.#

. (a) To what extent do different parts of the body develop at different rates? (b) Why might this be so?
** [hiddenAnswer]#(a) First brain/head which keep developing steadily until 12. Then lymphoid system peeks at age of 12. Finally, a bit later followed by height and reproductive system by 16. (b) For the puberty to initiate, the lymphoid system needs to develop substantially to support all the hormonal changes as well as the physical and mental development throughout the period, therefore they occur in different rates at different times.#

. (a) How has the emergence of different aspects of puberty changed over historical time, and (b) what is responsible for these changes?
** [hiddenAnswer]#(a) Menarche has not really decreased since 60s, breast development keeps decreasing (9 years). (b) It could be due to chemical components found in pesticides, medicine, fire retardants (dampening), tobacco, alcohol and obesity.#

. How does infants' behaviour reveal that they are actively exploring their environment with their eyes and that they remember what they have seen?
** [hiddenAnswer]#Babies look significantly longer at novel things. Looking less at familiar objects (habituation, dishabituation).#

. How does infants' behaviour reveal that they are motivated to control their environments and are emotionally involved in retaining control?
** [hiddenAnswer]#When babies are not in control of their environment in experiments anymore, they showed facial expressions of anger.#

. How do infants, beginning before 12 months of age, use their observations of adults’ behaviour to guide their own explorations?
** [hiddenAnswer]#They use gaze following (look where adult is looking) and shared attention (adult, baby, object relation). Social referencing happens after 12 months (look at adults to know how to "properly" respond).#

. (a) What is the *violation-of-expectation* method for studying infants’ knowledge of *physical principles*?
(b) With this method, what have researchers *discovered* about the knowledge of 2- to 4- month olds?
** [hiddenAnswer]#(a) First habituation (possible event), then an impossible events (e.g. rotating screen going "through" an obstacle) then potentially longer looking time indicating surprise. (b) Solid objects do not pass through other solid objects. Box falling down in mid air, but not capable of knowing box falls when put at the edge with most weight hanging off the shelf (only by 6 months).#

. (a) How did Jean Piaget *test* infants' understanding of *object permanence*?
(b) What might explain the *discrepancy* between Piaget's results and the results of *selective-looking* experiments?
** [hiddenAnswer]#(a) Make infants search for hidden objects (simple hiding problem): Hide an attractive toy, babies will lose interest as in it not knowing it's still there. With 6 months can solve this, but not "changed-hiding-place (A-not-B) problem": Same but move toy to yet another napkin. (b) Looking only can prove object permanence ability, whereas Piaget's test also required certain motor functions (which might not be yet developed).#

. What evidence suggests that self-produced *locomotion* promotes rapid development of infants' *search* abilities?
** [hiddenAnswer]#Three groups of infants: Crawling, walker-aids, non-crawling. 75% of first two succeeded with a (adapted) changed-hiding-place problem, compared to 13% of group three (non-crawling).#

. In Piaget's theory, how do schemes develop through assimilation and accommodation?
** [hiddenAnswer]#Assimilation: Take new XP into existing schemes. Accommodation: Schemes need to change/expand first to new XP.#

. (a) What is Piaget's "little scientist" view of children's behaviour? (b) How is it illustrated by the examples of an infant playing with containers and (c) by an experiment with preschool children allowed to play with a two-lever toy?
** [hiddenAnswer]#(a) Exploratory play, children like experiments with unknown objects = drawn to "assimilatable" XP which requires accommodation (a bit trickier wanted). (b) Stacking scheme, put containers on top of each other, one container has open top, and falls into it. Interesting (child plays longer with it) as it violates the stacking scheme and requires accommodation. (c) Toy given to children with two levers, each different effect. When shown separately the effect, not interesting as when shown both levers pulled, so children had to figure out themselves what does what. Better let children explore themselves, rather show/explain them. Concluding: Children's play is oriented toward discovery (not repetition of yet the known).#

. In Piaget's theory, what is the special value of *operations*?
** [hiddenAnswer]#Operations are reversible actions (most valuable for mental development). Building "operational schemes", thinking about reversibility. Value is: Understand basic physical principles. E.g. conservation of substance: clay ball turn into sausage and back, same liquid poured in different glasses.#

. In Piaget's theory, what are the *four stages* and the stages roughly associated with each?
** [hiddenAnswer]#Sensorimotor (-2), preoperations (-7), concrete operations (-11), formal operations (-16).#

. What are two ways, other than reversibility of operations, that preoperational and concrete operational children *differ*?
** [hiddenAnswer]#Preoperational more focused to perceptual field (concentration); use more perception than logic. Concrete-operational is less egocentric/selfish, more logical; can separate from specific aspects of perceptual array, make decisions based on entire perceptual field (deconcentration). Concrete-operational children can solve the "glass liquid problem" :)#

. Why do many of today's developmental psychologists *doubt* Piaget's theory of stages of mental development?
** [hiddenAnswer]#He underestimated infants and overestimated adults mental abilities. Children from different ages solved different staged-tasks. Details might be wrong, yet he contributed major findings (just like shakespeare to English literature and Aristotle to philosophy).#

. How does *Vygotsky*'s perspective on cognitive development *differ from Piaget's*?
** [hiddenAnswer]#More sociocultural perspective: Taking social and cultural environment into account (values, beliefs). More on social environment interaction, rather than physical environment. Nice story: Counting balls as a child, figuring out commutativity; Piaget emphasizes action, Vygotsky asks how comes he did that?" PS: He died at age 38.#

. (a) What is Vygotsky's concept of *tools of intellectual adaptation*? (b) How can such tools influence the course of *cognitive development*?
** [hiddenAnswer]#(a) Tools provided by social environment, abstract ones like numbers, alphabets, words; objects to write/calculate/record like pencils, books, computers. (b) .#

. (a) How might the number words of Asian languages help children learn the base-10 number system more easily than American and European children?
(b) What evidence suggests that they do learn the base-10 number system earlier?
** [hiddenAnswer]#(a) Numbers in asian languages (chinese, japanese, korean) have clues already about the base-10 system (instead "eleven" they say "ten one"). (b) Different colored blocks representing 10 and 1, Asian much more effectively distinguish them (80% success, european/US only 10%).#

. How might being a "digital native" influence how children today learn to think?
** [hiddenAnswer]#Bar.#

. What is the "zone of proximal development", and how does it relate to children's cognitive development?
** [hiddenAnswer]#Bar.#

. How does Vygotsky's "apprentice" view of child contrast with Piaget's "scientist" view?
** [hiddenAnswer]#Bar.#

. What is information-processing perspective on cognitive development, and how does it differ from Piaget's and Vygotsky's perspectives?
** [hiddenAnswer]#Bar.#

. Through what developmental steps do young children develop the capacity to form episodic memories?
** [hiddenAnswer]#Bar.#

. How do executive functions and speed of processing change with age during childhood and early adolescence?
How might working-memory capacity depend on speed of processing?
** [hiddenAnswer]#Bar.#

. What do children younger than 3 years old understand about other people's minds?
** [hiddenAnswer]#Bar.#

. hat evidence suggests that children younger than age 4 usually do not understand that people can hold false beliefs?
Why might false beliefs be particularly difficult for young children to understand?
** [hiddenAnswer]#Bar.#

. What logic and evidence suggest that engagement in pretend play, especially in role-play with other children, may help children acquire an understanding of false beliefs?
** [hiddenAnswer]#Bar.#

. How does research on people with autism support the premise that the understanding of minds and the understanding of physical objects are fundamentally different abilities?
** [hiddenAnswer]#Bar.#

. How does research on autism support the idea that an understanding of false beliefs may derive, in part, from prior engagement in pretend play?
** [hiddenAnswer]#Bar.#

. What are the universal characteristics of morphemes?
How do morphemes differ from nonverbal signs?
** [hiddenAnswer]#Bar.#

. How can any sentence, in any language, be described as a four-level hierarchy?
How can rules of grammar be described in relation to that hierarchy?
** [hiddenAnswer]#Bar.#

. What does it mean to say that knowledge of grammar is usually implicit rather than explicit?
** [hiddenAnswer]#Bar.#

. How have researchers shown that very young infants can distinguish between subtly different speech sounds?
How do infants' abilities to distinguish among such speech sounds change during the second half-year of their lives?
What is the value of these changes?
** [hiddenAnswer]#Bar.#

. What is the distinction between cooing and babbling?
What are the reasons for thinking that these vocalizations are precursors to language production?
** [hiddenAnswer]#Bar.#

. What is evidence that babies begin to understand words well before they begin to speak?
** [hiddenAnswer]#Bar.#

. How do young children make the link between new words that they hear and appropriate referents in their environments?
** [hiddenAnswer]#Bar.#

. What are two reasons why children might overextend common nouns that they have learned?
** [hiddenAnswer]#Bar.#

. How do children demonstrate knowledge of grammatical rules in their early speech?
How do some of their "mistakes" in grammar confirm that they know the rule and are not just mimicking?
** [hiddenAnswer]#Bar.#

. How did Noam Chomsky link the study of grammar to psychology?
What did he mean by a language-acquisition device?
** [hiddenAnswer]#Bar.#

. How have studies of creole languages and studies of deaf children in Nicaragua supported the idea that children invent grammar in absence of a pre-existing grammatical language?
** [hiddenAnswer]#Bar.#

. What evidence supports the view that grammar is learned more readily in early childhood than later in life?
** [hiddenAnswer]#Bar.#

. How do parents in our culture modify their speech to infants?
** [hiddenAnswer]#Bar.#

. What evidence suggests that differences in the language environments provided by parents can affect the rates at which infants acquire language?
** [hiddenAnswer]#Bar.#

. What light has been shed on the LASS by cross-cultural research?
** [hiddenAnswer]#Bar.#

. What is the distinction between simultaneous and sequential bilinguals?
** [hiddenAnswer]#Bar.#

. What are some of the costs and benefits of bilingualism relative to speaking only one language?
Do you think the costs outweigh the benefits?
** [hiddenAnswer]#Bar.#


== Think Critically

. (a) How can we know what an infant is thinking about? (b) Why or why not might it be worthwile to study perception and cognition in preverbal infants?
** [hiddenAnswer]#Bar.#

. (a) How are the child's capacities and limitations at each of Piaget's stages of development related to the kind of scheme that is most prominent? (b) How does the child's behavior at each stage promote advancement to the next stage?
** [hiddenAnswer]#Bar.#

. Some theorists propose that children play an active role in their own mental development, whereas others emphasize the role of a child's sociocultural environment in influencing cognitive development Are these approaches complementary or antagonistic to one another?
** [hiddenAnswer]#Bar.#

. To what extent is language development supported by inborn mechanisms and/or the social context?
** [hiddenAnswer]#Bar.#