= Focus Questions

. How would you construct a test to assess a person’s ability to perceive analogies?
** [hiddenAnswer]#Either verbally, as in "X is to Y, as A is to ..." or visually with a Raven's problem (finish the sequence of graphics).#

. What is some evidence concerning the usefulness of analogies in scientific reasoning?
** [hiddenAnswer]#Charles Darwin, Johannes Kepler, both found their findings through analogies. Neuroscience used computer analogy to progress in understanding.#

. (a) How are analogies useful in judicial and political reasoning?
(b) What distinguishes a useful analogy from a misleading one?
** [hiddenAnswer]#(a) It makes it easier to understand for the audience, as it is more concrete/tangible/reachable rather abstract. (b) As long as structural relationships hold true it's useful, otherwise it's misleading.#

. (a) What is inductive reasoning, and (b) why is it also called hypothesis construction?
(c) Why is reasoning by analogy inductive?
** [hiddenAnswer]#(a) Infer new knowledge/principles by observing facts that serve as clues (from the specific to the general). (b) As it is an educated guess, and not certain/definite. (c) As it is founded by perceived analogies/similarities, based on (past) experiences, in order to compare things.#

. What kinds of false inferences are likely to result from the availability bias?
** [hiddenAnswer]#When relying on information which is available (VS ignore information which is less available), e.g. mass media.#

. What are two different ways by which researchers have demonstrated the confirmation bias?
** [hiddenAnswer]#(1) Take the sequence "2 4 6" and tell me the rule. People will try to verify, rather disprove their hypothesis. (2) The way researchers ask questions to subjects can influence the expected outcome. Suggestive questions like "Do you like/Do you feel shy about meeting new people?"#

. How does a die-tossing game demonstrate the predictable-world bias?
** [hiddenAnswer]#People go instead for maximizing (dices with 4 red and 2 green, thus going for red all the time), for matching (varying guesses matching the probability, 66% red, 33% green).#

. (a) How does deductive reasoning differ from inductive reasoning?
(b) How is it illustrated by series problems and syllogisms?
** [hiddenAnswer]#(a) Deductive is from general to specific, is safe, and doesn't create new info as it only uses logical consequences. Inductive is from specific to general, is unsafe as it uses reasoning guesswork, but creates new info. (b) Deduction concludes results from given conditions (series problem). With syllogisms info overlaps, which makes it possible to conclude results (or at least indeterminate).#

. What is evidence that the tendency to rely on real-world knowledge can overwhelm our deductive-reasoning ability?
** [hiddenAnswer]#We focus on the truth of the statement/conclusion (our knowledge), rather than relying on the deductive reasoning (logic) based on the given premises. We have hard time separate those two. See example with living-water-roses vs insects-oxygen-mice.#

. To what extent is the *design stance* with respect to *tools* (a) a limitation to human cognition or (b) an adaptation?
** [hiddenAnswer]#Design stance: Every tool has a function assumption. (a) Functional fixedness, everything which looks like a fork, we imagine only being used as a fork. (b) We don't have to go through trial-and-error, but know immediately how to use it making us very efficient (at cost of some flexibility).#

. (a) What evidence suggests that solving *insight* problems is qualitatively different from *deductive* reasoning?
(b) How might mental *priming* be involved in achieving *insight*?
** [hiddenAnswer]#(a) Insights uses time off ("incubation") not thinking about the problem, but deduction requires conscious attention, it's effortful, it's "slow thinking", as Kahnemann would put it. (b) Primed concepts may form new unconscious associations which help to get insights.#

. (a) What evidence suggests that happiness or playfulness helps to solve insight problems?
(b) According to "broaden-and-build" theory, how do positive emotions differ from negative emotions in their effects on perception and thought?
** [hiddenAnswer]#(a) Let people solve candle test after watching happy/sad movie, with happy movie they achieve better results. (b) Negative emotions narrow perception/thought, focus on emotion-evoking objects, think of routine/well-learned ways of responding. Positive emotions broadens perception/thought, increased creativity (when there is no danger, all needs satisfied; now it's the time to explore/be creative, to prevent future emergencies).#

. (a) How do unschooled members of non-Western cultures typically perform on classification problems?
(b) Why might we conclude that differences in classification are based more on preference than on ability?
** [hiddenAnswer]#(a) They grouped more likely by practical/functional terms ("by function"), rather in terms of abstract properties ("by nature/type"). (b) Because the daily tasks/the environment requires it (habit, culture), but they are still able (to group by nature) if asked to (do it like "stupid people").#

. (a) How have researchers documented a general difference between Westerners and East Asians in perception and memory?
(b) How might this difference affect reasoning?
** [hiddenAnswer]#(a) West: individual characteristics, analytical, detail, exoteric, entities abstracted from background. East: big picture, whole scene, interrelationships, holistic, esoteric. Easteners can also remember more (not only large entities), but also smaller, less active objects. Documented by the aquarium fish test (what focus/remember in scenery), and the frame-line test (absolute task of 30mm, relative task of 1/3, whereas the total is 90mm; westerns better at absolute, easteners better at relative). (b) Reasoning is influenced by our focus/perception, thus the conclusion being drawn are different. Westeners: Causal consequence of separate events. Focus on single, absolute details. Easteners: An organic wholeness which acts as a transactional system. Focus on the whole, the whole box, thus being able to relate a size.#

. (a) What sorts of subtests make up modern IQ tests, such as the Wechsler tests, and (b) how is IQ determined?
** [hiddenAnswer]#(a) Verbal comprehension, perceptual processing, working memory and processing speed. (b) By a standardized scoring, using a normal distribution (assuming people's intelligence is distributed like it), and 100 being that average.#

. (a) How have psychologists assessed the validity of IQ tests?
(b) What are the general results of such assessments?
** [hiddenAnswer]#Bar.#

. (a) What was Spearman’s concept of general intelligence, or g?
(b) Why did Spearman think that g is best measured with a battery of tests rather than with any single test?
** [hiddenAnswer]#Bar.#

. What evidence led Cattell to distinguish between fluid intelligence and crystallized intelligence?
** [hiddenAnswer]#Bar.#

. What findings have revived Galton’s idea of mental quickness as a basis for general intelligence?
** [hiddenAnswer]#Bar.#

. (a) How might executive functions provide a basis for individual differences in intelligence, and how might mental quickness affect that capacity?
(b) What evidence supports this logical possibility?
** [hiddenAnswer]#Bar.#

. What reasoning suggests that general intelligence is an adaptation for dealing with evolutionarily novel problems?
** [hiddenAnswer]#Bar.#

. (a) What is the difference between the absurd form of the nature-nurture question and the reasonable form?
(b) Why is one absurd and the other reasonable?
** [hiddenAnswer]#Bar.#

. (a) How is heritability defined?
(b) Why would we expect heritability to be higher in a population that shares a similar environment than in an environmentally diverse population?
** [hiddenAnswer]#Bar.#

. (a) What is the logic of comparing identical and fraternal twins to study the heritability of traits?
(b) What difference is observed between identical and fraternal twins in IQ correlation?
** [hiddenAnswer]#Bar.#

. How can IQ heritability be estimated using the correlation coefficients for the IQs of identical and fraternal twins raised together?
** [hiddenAnswer]#Bar.#

. How can IQ heritability be estimated by studying identical twins who were adopted into different homes?
** [hiddenAnswer]#Bar.#

. How can a person's rearing environment influence the heritability of IQ?
** [hiddenAnswer]#Bar.#

. (a) What is the evidence that the effect of a shared family environment on IQ correlations is lost in adulthood?
(b) How might this loss be explained?
** [hiddenAnswer]#Bar.#

. What evidence suggests that intellectual involvement can increase a person’s fluid intelligence over time?
** [hiddenAnswer]#Bar.#

. Why can't heritability coefficients found within groups be used to infer the source of differences between groups?
** [hiddenAnswer]#Bar.#

. What evidence suggests that the average IQ difference between black and white Americans derives from the environment, not genes?
** [hiddenAnswer]#Bar.#

. What is stereotype threat, and how does it explain differences in IQ between white and black Americans?
** [hiddenAnswer]#Bar.#

. What evidence suggests that the status of being an involuntary minority may be particularly detrimental to IQ development?
** [hiddenAnswer]#Bar.#

. (a) How does history provide further evidence that IQ is highly susceptible to cultural influence?
(b) On which measures has IQ increased the most?
** [hiddenAnswer]#Bar.#

. How might the historical increase in fluid intelligence scores be explained?
** [hiddenAnswer]#Bar.#

== Think Critically

. (a) What is meant by "intelligence" and (b) to what extent are levels of intellectual functioning influenced by nature versus nurture?
** [hiddenAnswer]#(a) Bar. (b) Bar.#

. (a) Is it reasonable to contrast the cognitive abilities of people from different cultures? (b) What aspects of human thinking are characteristics of the species (species universal) versus dependent upon the culture one is brought up in (culture specific)?
** [hiddenAnswer]#Bar.#
