= Self-Compassion

== Guided Practices

https://self-compassion.org/self-compassion-practices/#guided-practices

. *General Self-Compassion Break*
** The link:https://selfcompassion.web.unc.edu/what-is-self-compassion/the-three-components-of-self-compassion/[3 components] of self-compassion.
... Self-kindness (vs. self-judgment): being warm and understanding when you suffer/fail/feel inadequate. Avoid self-criticism or ignoring the pain. Be gentle with yourself instead of getting angry for falling short.
... Common humanity (vs. isolation): All humans suffer, it's not only me, I'm not special with this kind of struggle. Humans are, by definition, mortal, vulnerable, and imperfect; it's part of our shared human experience.
... Mindfulness (vs. over-identification): Allow and observe also the uncomfortable thoughts/emotions (don't suppress or exaggerate them), with openness and clarity, in mindful awareness. We cannot ignore our pain and feel compassion at the same time; not getting swept away by negative reactivity.
** Focus on one single event that causes you distress (social conflict, worries).
** Be mindful of what's going on, tell yourself: "_I'm suffering right now because of this._", "_I'm in pain, I feel lonely and am desperate._"
*** Don't deny it, as "to resist is to persist."
** Use a soothing touch; e.g.: a hand on chest/sternum or belly.
** Talk to yourself, to your inner child, as if you talk to your best friend, support him.
*** "_This too will pass, you are now in pain, and it will go away. You are safe with me, I see you._"
*** Maybe use your first- or a nickname to refer to yourself: "_Dear xxx, I wish you will be happy soon again._"
. *Tender Self-Compassion Break*
** Accept yourself and your difficult emotions when needing comfort/soothing.
** Mindfulness, acceptance, present with what is, validating it.
*** "I feel tensed and frustrated because I didn't get what I want. I feel hurt, and lonely."
** Kindness, a soothing touch, on chest area or face. Hold yourself, support yourself.
** Encouraging words, as if you would talk to a friend.
*** "It must be hard to go through this situation. I can imagine you are desperate, and feel treated with injustice."
*** "You will be ok, you will manage, you always did. You are strong, I believe in you. Those are hard times, but you are harder."
. *Protective Self-Compassion Break*
** Be aware, acknowledge, accept of what happened: Crossed boundary, threatened, pushed down, ...
*** Focus on the harm being done, not on the person.
** Draw from the "collective strength".
*** Others went through the same, "me too".
** Symbolize the heart-courage: fist on heart, tender palm around fist.
*** Set a boundary, be proactive, take care of yourself.
*** Use fierce, and embodied clarity.
. *Providing Self-Compassion Break*
** Identify and label the need in situation which was not met.
** Remind yourself that your needs matter.
*** There is a balance in giving and receiving.
*** All our needs matter, everyone's do, including my own.
** Touch your solar-plexus, and draw energy from their.
** Do what's necessary to come in action, to take care of your needs being met.
. *Motivating Self-Compassion Break*
** Be mindful about what you want to change in your life.
*** Is it more friends? Get this project running you always desired? Unhappy relationship?
** Put a hand on your shoulder, like you would at a colleague to support him.
** Use supportive sentences to encourage that change.
*** Imagine you'd talk to a friend, use the same language also to yourself.
*** E.g.: "You can do it, you managed in the past, you will also manage this time."
** Merge unconditional self-acceptance, and still strive for that necessary change.
*** The way you are, as a human being, you are good enough, okay the way you are; imperfection is human.
*** The circumstances, the behavior needs some attention to change.
. *Soles of the Feet*
** Standing, feeling feet on the ground; shift weight, pay attention to sensations there.
** Walking, feeling again the shift of the weight.
** Stand again, come to rest.
. *Soften, soothe, allow: Working with challenging emotions*
** First calm down, observe and then deepen breaths.
** Think of a challenging situation with uncomfortable emotions.
** Follow these 3 steps:
... Where in the body do you feel the arising emotions? Which sensations?
... Put a tender, soft hand there, and softening there, let go of tightness/restriction.
... Sooth yourself, acknowledge the way you feel right now: "_This hurt me. I felt frustrated and was in deep pain. It's ok, you are safe right now_"
** Let it melt away, accept whatever there is, allow yourself to feel and simply observe, breathe and feel the bodily sensations and experienced emotions.
*** We have an in-born tendency to avoid pain, but "to resist is to persist" and the emotion gets only more intense; instead try to face the emotion, and acknowledge, even welcoming it; sooften, sooth, and allow.
. *Noting Practice*
** A typical mindfulness journey.
** Watch your breath.
** Tap into physical sensations; feel your body touching the ground, tension, temperature, wind.
** What can you hear? No need to label, to identify the source, just be aware. Birds, people, city, wind...
** What thoughts and emotions are present? No need to dive into them, to hold on to them. Just be aware.
** Lastly, watch your breath again.
. *Compassionate Friend*
** Feel your body, where it touches the ground.
** Put a soothing hand/hands on your body (heart area, belly).
** Imagine a safe space, where you feel protected, at ease, calm.
** Imagine a friend sharing words of wisdom full of kindness.
** Coming back to the safe space again.
** Realizing all of those things is you.
. *Fierce Friend*
** Be aware of your breath, optionally put one or two hands on your body (belly and chest); feeling the ground.
** Travel to your imaginary safe place (a house, castle, beach, forrest).
** Imagine a fierce friend shows up, whether someone you know or something made up, like a strong warrior or a wise priestess.
** What would that friend say to you? Words of wisdom and kindness.
** Something materializes in your hand from this friend. What is it?
** Realize that this is all you. That friend is within you.
** Let go of the imagination, focus on the breath.
. *Balancing Yin and Yang*
** Arrive in your body, take a few deep breaths, close your eyes.
** Round 1: Yang
*** Make a fist as a psychological support and put it on your body.
*** Focus on your in-breathe, visualize fierce energy flowing into your body from the root of your spine.
** Round 2: Yin
*** Put a palm on your chest for support.
*** Focus on your out-breathe, visualize tenderness helping you to let go, relax.
** Round 3: Yin+Yang
*** Put both a fist and a palm on your body as support.
*** Focus on both your in- and out-breath.
. *Giving and Receiving Compassion*
** Arrive at the moment, being aware of your body.
** Put one or two hands on your body, expressing kindness, for example, on your heart.
** Focus on your breath; first on the in-breath, to receive compassion.
*** Breathe in everything you want more in your life: compassion, happiness, joy.
** The focus on your out-breath, to give compassion.
*** Breathe out anything that you want less in your life.
. *Affectionate Breathing*
** Focus on warmth and goodwill, generate affection and kindness; for yourself and others.
** Hand on your heart area, feeling the warmth there.
** Have a half-smile throughout the whole session.
. *Compassionate Bodyscan*
** Go through your body, just as in a regular bodyscan.
** Give appreciation for what it has done for you. Compassionate what it has been through.
** Do that part by part.
. *Loving-Kindness Meditation* 💙
** Arrive, taking a few deep breaths, let go of what happened during the day.
** Round 1: Find a person you feel safe with (family, partner/friend, mentor), no difficult emotions with, unconditional love, care, and compassion.
*** Wish them all the best by saying the following: "_May you be safe. May you be peaceful. May you be healthy (mind and body). May you live with ease (and well-being)._"
*** If that person has currently a hard time, add at the end "_... if possible_".
** Round 2: Do the same but for the both of you: "_May we be safe..._"
** Round 3: Do it for yourself: "_May I be safe..._"
** Round 4: Do it for someone you don't know that well.
** Round 5: Slowly extend to bigger groups: District, town, country, planet; at last, include every living being, plants and insects.
. *Self-Compassion/Loving-Kindness Meditation*
** Lie or sit down, take a few deep breaths to land.
** Think of a recent situation you felt uncomfortable with. A mistake you made.
*** Feel your body's response: contraction in the chest, tension in the shoulders, tightness in the throat, ...
*** Be aware of the emotions and thoughts you have about this situation.
** Put one or two hands on your sternum, your heart center, maybe stroke it a bit to sooth yourself.
** Then say the following: "May I be safe. May I be peaceful. May I be kind to myself. May I accept myself as I am".
*** Do the same also for "we".
** Remember that "to err is human", it is part of the human condition to make mistakes.

== Heart Coherence Training

link:https://www.youtube.com/watch?list=PL9rlR6zIwFY4ZoOJMdLo-3Fl1PvPAeN6-[Full list] (German) of 10 YouTube videos.

=== Explanation

Introduction to link:https://www.youtube.com/watch?v=zvcEybr6jKk[Guided Conscious Breathing Session]

* Three important aspects of such a (integrative breathwork) session:
** Grounding: I'm being carried, whatever wants to be expressed, it's allowed to be there; earth receives everything that happens.
** Breath: Flows from one moment to the other, it leads the process.
** Guide: "Spaceholder", attentive and present part of the process; supports by simply being there.
*** Creates a safe space, to allow yourself to explore unknown parts of yourself.
* Daily breath is barely enough to survive, staying within comfort zone, to live a conforming life -don't stick out too much.
** If you want to grow my potential, going beyond the comfort zone: Step beyond the borders, into the unknown -scary!
** Increase lung-volume by breathing deeper (chest and belly); or breath faster than usual.
* A lot can happen, all kind of emotions: sadness, pain, joy, anger, ...
** Accept whatever there is, giving it a good place in my life, creating a new order, creating more space in life, more flexibility/freedom.

=== Coherence Training Exercise

link:https://shop.ulieckardt.de//2013/11/kohaerenztraining/[Source]

* Effect:
** It will balance the sympathetically and the para-sympathetically nervous system.
** This will lead to a more regularly (coherent) heartbeat.
*** When we are stressed or under any other emotional pressure, the heartbeat frequency is more chaotic.
* Preparation:
** As it is a relaxation exercise, it has to be done in a calm, quiet, peaceful environment (no phone, bells, people).
** It is possible to play relaxing (meditation) music in the background.
** Wear comfortable clothes (nothing too tight); e.g. shoes, belts, bra.
** Lie on a couch or bed, close your eyes.
* Comments:
** Do it several (3-5) times per week, for at least 1 month; it won't take more than 10mins.
** Ensure proper aftercare: no phone or media right afterwards, "wake up" slowly.
* Instructions:
** 5x: Take a deep breath, hold shortly after the inhale, exhale double length as usually; count 1-3 in your thoughts.
** Focus on heart area, positive air streams in.
*** Imagine fresh air coming into your body with every inhale. Air full of life, health, balance.
*** Optionally, imagine a color of that air, and how it colorizes your heart area.
** Exhale everything negative that bothers you.
*** Optionally, give it a color and shape.
*** Feel how it leaves your body with every breath. Feel how you relax more and more.
** _Stay with this part for several minutes..._
** Imagine how your heart is touched by a fresh breeze of wind at the sea/of a mountain river.
*** Optionally, imagine something from a wonderful holiday. (beach, mountaines)
*** Imagine a scenery, while you inhale fresh, wonderful air, and exhale all negativity.
** Feel how your heart softens, how it regenerates, how it relaxes when inhaling, how positive charged air enters your body.
*** Awaken the peace and gratitude inside yourself. The love to yourself.
*** Feel relaxation and lightness expanding in your body, comfortably warmth and how it feels good for you.
** Feel safe, loved. Love yourself the way you are. Feel the joy of life.
*** Let all those wonderful sensations and feelings enter every cell of your body. Let them enter your mind, your soul.
*** Optionally, give those sensations/feeelings/images a color, and let that color expand everywhere.
** Continue breathing deep and slowly. _Stay with this part for several minutes..._
*** Let the feelings get more and more clear, while your heartbeat gets calmer and more regular.
*** No need to force it, let it happen, it will happen by itself, effortlessly, just surrender.
*** You are doing this well. You are good the way you are. Feel the unconditional love inside of you.
** Realize: All those positive sensations/feelings/emotions/and impressions, you created yourself, inside yourself.
*** You alone are the architect of all these wonderful sensations.
*** They also stay as long as you want them to stay inside of you.
*** Even when now all those sensations start to disappear from your eyes, heartarea and body.
*** Let that sensation take care that you feel your body again, be aware of your surroundings/the room.
** Be aware of the relaxation in your body.
*** How energized/recharged you feel, full of energy and enthusiasm.
*** Slowly open your eyes.

=== Meditation

link:https://www.youtube.com/watch?v=fAI1OH1NNlU[Instructions] by Ulrich Eckardt

* What is it?
** A relaxation exercise taking about 15 minutes.
** Balancing between sympathetically and para-sympathetically nervous system.
** So that the heart beats in a calm and regular rhythm = state of heart coherence.
* How to do it?
** Do the exercise in a calm space (no notifications, get rid of any disturbances).
** Only while lying down.

Instructions for the meditation (starting at link:https://youtu.be/fAI1OH1NNlU?si=rCxDwhILQjQyh0ar&t=187[3:07])

* Find a comfortable position
** Close your eyes
* "Cyclic breathing":
.. Deep inhale.
.. Hold for a moment.
.. Exhale double length than usual.
.. Hold while counting from 1 to 3.
** Focus on heart area; how "positive air streams inside you".
** While *inhaling*:
*** Imagine how fresh air comes in; air of health, balance, serenity, full of life energy, relaxation and confidence.
*** Imagine air having a certain color, and how that color protects your heart area.
** While *exhaling*:
*** All negative gets breathed out.
*** Imagine that negativity has a shape and a color.
*** Feel how the heaviness leaves your body, and you are getting more relaxed.
** Keep on doing this breathing for a few minutes...
* Imagine a fresh breeze on the beach, good air into your body, nourishing and relaxing you.
** Feel warmth, gratitude, love to yourself, and compassion expanding.
** Feel safe and accept the way you are. Joy and quality of life.
** Let those feelings stream into your body, becoming one with your mind.
** Give those sensations a color, and let that color stream through your whole body.
** Focus and allow emotions, be mindful of the slowing down of breath and heartbeat.
** Stay with this part of the exercise for a few minutes..
* Remember that it was you yourself who created all these sensations!
** You are the creator, the architect of those positive feelings.
** Slowly realize where you are, waking up, remembering the positivity and energy in your body.
** Slowly open your eyes.
