= Focus Questions

. How did *Clever Hans* give the *appearance* of answering questions, and how did Oskar Pfungst *unveil* Hans' methods?
** [hiddenAnswer]#By correctly reading unconscious hints of the audience.
By a series of field-experiments and observations which disabled Hans to see, which lead to a drop of his success rate, leading to the conclusion that Hans did not actual solve the problems himself.#

. How are *observations, theories and hypotheses* related to one another in scientific research?
** [hiddenAnswer]#According to the book: It starts with an observation, which is an objective statement, then we develop a theory (an idea, a conceptual model), based on which a prediction is made, a so-called hypothesis.#

. How does the Clever Hans story illustrate (1) the value of *skepticism*, (2) the value of *controlled experimentation*, and (3) the need for researchers to avoid communicating their *expectations* to subjects?
** [hiddenAnswer]#(1) Although everyone believed Hans and there seemed to be proof, doubting and assuming one is wrong, always trying to disprove oneself, can lead to exposure of wrong believes.
It stimulates critical thinking, although it might lead to discomfort, but as a philosopher we are in search for the truth, for knowledge, rather comfort ourselves. (2) By changing the dependent variable one-by-one, until he introduced blinders as the only changing controlled variable, so he could measure it.
Kind of an application of an exclusion principle. (3) Because the observers (researches, audience) had an unconscious desire that Hans will know the right answer, they unconsciously communicated the right answer to him via subtle cues.
This is known as the expectancy bias (observer/subject-expectancy effect).#

. How can an *experiment* demonstrate the existence of a *cause-effect* relation between two variables?
** [hiddenAnswer]#By controlling "all" other variables and eliminating their effect on the outcome, leaving the cause to only a single variable.#

. What were the in/dependent *variables* in Pfungst's experiment with *Clever Hans*?
** [hiddenAnswer]#In his final experiment, Pfungst used the blinder as an independent variable and Hans' response (tapping of his hoof) as the dependent variable.#

. What were the in/dependent *variables* in DiMascio's experiment on treatments for *depression*?
Why were the subjects *randomly assigned* to the different treatments rather than allowed to choose their own treatment?
** [hiddenAnswer]#The dependent variable is the depression score, whereas the independent type of treatment.
To counteract personal preferences/differences of subjects which exist already before the study.
For example all the highly depressed use drugs as they want to avoid personal contact.#

. What are the differences in procedure between a *correlational study* and an *experiment*?
How do the types of conclusions that can be drawn differ between a correlational study and an experiment?
** [hiddenAnswer]#Correlational is passively observing, whereas experiment is actively controlling variables.
Correlational can make predictions, whereas experiments can tell about cause-effect.#

. How does an analysis of Baumrind's classic study of *parental disciplinary styles* illustrate the difficulty of trying to infer *cause-and-effect* from a *correlation*?
** [hiddenAnswer]#It was not an experiment as there was no control of the variables.
It influence could be the other way round (child's behavior affecting parenting style) and also genetical differences lead to different personalities and behaviors.#

. How do *descriptive studies* differ, in method and purpose, from experiments and from correlational studies?
** [hiddenAnswer]#They don't assess the relationship between variables, they can't explain cause-and-effect (correlation), it's a prosa text with possibly making use of numbers.#

. What are the relative dis/advantages of *laboratory/field studies*?
** [hiddenAnswer]#Pro lab: Full control of the environment; Con Lab: Possible different behavior due to artificial environment; Pro field: Natural environment; Con field: Uncontrollable environment#

. How do *self-report* methods, *naturalistic observations*, and *tests* differ from one another?
What are some dis/advantages of each?
** [hiddenAnswer]#Self-report (introspection, questionaire, interview); Observational (naturalistic, tests); self-reports are highly subjective; naturalistic observations avoid any interfering; tests might be already biased by the researcher on the way they are set up, they are not very subjective as subject is acting without introspection.
TODO difficult one! review this one!#

. How do the mean, median and standard deviation help describe a set of numbers?
** [hiddenAnswer]#The standard deviation shows how different numbers are (variation; from the mean), how many extremes there are; if it is high, ("usually") better use the median as it is robust against extremes (relates more to reality), otherwise the mean is safe to use (depends on the goal, e.g. when evaluating the taxes, mean is better).#

. How does a *correlation coefficient* describe the direction and strength of a correlation?
How can correlations be depicted in *scatter plots*?
** [hiddenAnswer]#If it is abs(high), closer to 1, then correlation is strong (dots closer to the line, inferrable; otherwise more chaotic/unpredictable), when it is positive then the correlation itself is positive (upwards line).#

. Why is it necessary to perform inferential statistics before drawing conclusions from the data in a research study?
** [hiddenAnswer]#Because experiments can rely on results based on pure chance (random, uncontrollable variables); repeating them could lead to different results, drawing wrong conclusions; it uses laws of probability to counteract this phenomena.#

. What does it mean to say that a result from a research study is *statistically significant* at the 5% level?
** [hiddenAnswer]#p = probability / level of significance / chance, randomness; The conclusion drawn from data can be by chance only for less 0.05/5% of the entire set.
TODO rephrase#

. How is statistical significance affected by (1) the size of the effect, (2) the number of subjects or observations, and (3) the variability of the scores within each group?
** [hiddenAnswer]#(1) large effect-size more likely to be significant, less chance (2) in case there is significance, increasing the number will lead to more statistical significance, less chance; also will be more accurate (3) comparing groups with each other with an index of variability (e.g. standard deviation) the less, the more significant.#

. What is the difference between random variation in behavior and bias, and why is bias the more serious problem?
** [hiddenAnswer]#Random variation is a natural phenomena on average correct, the bias whereas is a fault in the approach/method being used.
Random variation can, but bias cannot be identified and corrected by statistical techniques and also can lead to false conclusions.#

. How can a non-representative selection of research subjects introduce bias ino (a) an experiment and (b) a descriptive study?
** [hiddenAnswer]#(a) Biased results can result because of **preexisting differences** in people's choices. (b) The description will not represent the **larger population**.#

. (a) What is the difference between the **reliability** and the **validity** of a measurement procedure?
(b) How can lack of validity contribute to bias?
** [hiddenAnswer]#(a) Reliability is about being reproducable (a measurement error, not bias), whereas validity is about doing what it meant to do.
(b) As the wrong measurement (invalid) lead to wrong conclusions (bias).#

. How can we assess the **validity** of a **measurement procedure**?
** [hiddenAnswer]#By **correlating its scores** with another, more direct index (criterion) of the characteristic that we wish to measure/predict (criterion validity).
E.g.: statement IQ=success, one successful, other not; if IQ differs, then valid.#

. How can the supposed phenomenon of **facilitated communication** by people with autism be explained as an **observer-expectancy effect**?
** [hiddenAnswer]#Unconscious influence, due to motivation to believe/expectations, of facilitators.#

. (a) What are two ways by which an **observer's expectations** can bias results in a typical experiment?
(b) How does **blind observation** prevent such bias?
** [hiddenAnswer]#The observer's behavior is unconsciously different and influencing the subject's behavior, or the observer's expectation can influence perception/judgement.
Because where there is no knowledge about aspects of the study's design, there can't be expectations.#

. (a) How can **subjects' expectancies** bias the results of an experiment?
(b) How does a **double-blind** procedure control both subjects' and observers' expectancies?
** [hiddenAnswer]#(a) By knowing about aspects of the study (e.g. treatment type), the subject's believes changes, thus the behavior, feeling and judgement.
(b) By not telling neither party, keeping them blind, the study's design, there will be no expectation.#

. (a) What are the **ethical concerns** regarding privacy, discomfort, deception, and animal welfare in psychological research?
(b) How do researchers strive to minimize problems related to these concerns?
** [hiddenAnswer]#(a) Privacy: Ensure anonymity, not sharing any information.
Discomfort: Really necessary; outweights benefit; free to quit.
Deception: Sometimes lying is necessary; benign "white lies", clear up in debriefing.
Animal welfare: Balance suffering from benefit; nothing unnecessary.
(b) Proper de/briefing, inform as much as possible, inflict only as much suffering as necessary and justified.#

== Think Critically

. If we know that correlation does not imply causality, is there any scientific benefit of **correlational research**?
** [hiddenAnswer]#Yes, it gives us at least a hint.
It gives us numbers in order to be at least bit more of a natural science, thus better base for arguments.#

. Thomas Jefferson stated, "_An educated citizenry is a vital requisite for our survival as a free people_." How might an understanding of research methodology play a role in today's "**educated citizenry**"?
** [hiddenAnswer]#It makes us able to question/challenge anything given to us by critical thinking, whether by authorities like the government, the church or science.
We have the ability to freely choose what to believe in, rather than to blindly follow like sheep.#
