= Focus Questions

. What are the three *phases of prenatal development* and what are the major milestones of each phase?
** [hiddenAnswer]#1) Zygotic (germinal): Sperm fertilizes the egg, travels to uterus for two weeks, implanting to uterine wall. 2) Embryonic: Week 3-8, major organ systems develop. 3) Fetal: Week 9+ (about 38 weeks), growth/refinement of organs/body structure.#

. When is the unborn child most susceptible to the effects of *teratogens* and why?
** [hiddenAnswer]#During embryonic, preventing an organ (kidney, hands, feet) from developing properly, as most differentiation is happening here (drastic effect!).#

. How might *prenatal experience* "prepare" a fetus for postnatal life?
** [hiddenAnswer]#Those experiences can be used as a "forecast" of the future environmental condition. E.g. when pregnant women have poor diets, they give birth to "thrifty phenotypes", babies who store fat more easily. Or when mothers are exposed to stress, babies will more likely be anxious/fearful/impulsive/reduced executive functions/etc. Not all can be seen as bad, e.g. aggression/risk taking could be a preparation for the (hostile) environment.#

. (a) To what extent do different parts of the body develop at different rates? (b) Why might this be so?
** [hiddenAnswer]#(a) First brain/head which keep developing steadily until 12. Then lymphoid system peeks at age of 12. Finally, a bit later followed by height and reproductive system by 16. (b) For the puberty to initiate, the lymphoid system needs to develop substantially to support all the hormonal changes as well as the physical and mental development throughout the period, therefore they occur in different rates at different times.#

. (a) How has the emergence of different aspects of puberty changed over historical time, and (b) what is responsible for these changes?
** [hiddenAnswer]#(a) Menarche has not really decreased since 60s, breast development keeps decreasing (9 years). (b) It could be due to chemical components found in pesticides, medicine, fire retardants (dampening), tobacco, alcohol and obesity.#

. How does infants' behaviour reveal that they are actively exploring their environment with their eyes and that they remember what they have seen?
** [hiddenAnswer]#Babies look significantly longer at novel things. Looking less at familiar objects (habituation, dishabituation).#

. How does infants' behaviour reveal that they are motivated to control their environments and are emotionally involved in retaining control?
** [hiddenAnswer]#When babies are not in control of their environment in experiments anymore, they showed facial expressions of anger.#

. How do infants, beginning before 12 months of age, use their observations of adults’ behaviour to guide their own explorations?
** [hiddenAnswer]#They use gaze following (look where adult is looking) and shared attention (adult, baby, object relation). Social referencing happens after 12 months (look at adults to know how to "properly" respond).#

. (a) What is the *violation-of-expectation* method for studying infants’ knowledge of *physical principles*?
(b) With this method, what have researchers *discovered* about the knowledge of 2- to 4- month olds?
** [hiddenAnswer]#(a) First habituation (possible event), then an impossible events (e.g. rotating screen going "through" an obstacle) then potentially longer looking time indicating surprise. (b) Solid objects do not pass through other solid objects. Box falling down in mid air, but not capable of knowing box falls when put at the edge with most weight hanging off the shelf (only by 6 months).#

. (a) How did Jean Piaget *test* infants' understanding of *object permanence*?
(b) What might explain the *discrepancy* between Piaget's results and the results of *selective-looking* experiments?
** [hiddenAnswer]#(a) Make infants search for hidden objects (simple hiding problem): Hide an attractive toy, babies will lose interest as in it not knowing it's still there. With 6 months can solve this, but not "changed-hiding-place (A-not-B) problem": Same but move toy to yet another napkin. (b) Looking only can prove object permanence ability, whereas Piaget's test also required certain motor functions (which might not be yet developed).#

. What evidence suggests that self-produced *locomotion* promotes rapid development of infants' *search* abilities?
** [hiddenAnswer]#Three groups of infants: Crawling, walker-aids, non-crawling. 75% of first two succeeded with a (adapted) changed-hiding-place problem, compared to 13% of group three (non-crawling).#

. In Piaget's theory, how do schemes develop through assimilation and accommodation?
** [hiddenAnswer]#Assimilation: Take new XP into existing schemes. Accommodation: Schemes need to change/expand first to new XP.#

. (a) What is Piaget's "little scientist" view of children's behaviour? (b) How is it illustrated by the examples of an infant playing with containers and (c) by an experiment with preschool children allowed to play with a two-lever toy?
** [hiddenAnswer]#(a) Exploratory play, children like experiments with unknown objects = drawn to "assimilatable" XP which requires accommodation (a bit trickier wanted). (b) Stacking scheme, put containers on top of each other, one container has open top, and falls into it. Interesting (child plays longer with it) as it violates the stacking scheme and requires accommodation. (c) Toy given to children with two levers, each different effect. When shown separately the effect, not interesting as when shown both levers pulled, so children had to figure out themselves what does what. Better let children explore themselves, rather show/explain them. Concluding: Children's play is oriented toward discovery (not repetition of yet the known).#

. In Piaget's theory, what is the special value of *operations*?
** [hiddenAnswer]#Operations are reversible actions (most valuable for mental development). Building "operational schemes", thinking about reversibility. Value is: Understand basic physical principles. E.g. conservation of substance: clay ball turn into sausage and back, same liquid poured in different glasses.#

. In Piaget's theory, what are the *four stages* and the stages roughly associated with each?
** [hiddenAnswer]#Sensorimotor (-2), preoperations (-7), concrete operations (-11), formal operations (-16).#

. What are two ways, other than reversibility of operations, that preoperational and concrete operational children *differ*?
** [hiddenAnswer]#Preoperational more focused to perceptual field (concentration); use more perception than logic. Concrete-operational is less egocentric/selfish, more logical; can separate from specific aspects of perceptual array, make decisions based on entire perceptual field (deconcentration). Concrete-operational children can solve the "glass liquid problem" :)#

. Why do many of today's developmental psychologists *doubt* Piaget's theory of stages of mental development?
** [hiddenAnswer]#He underestimated infants and overestimated adults mental abilities. Children from different ages solved different staged-tasks. Details might be wrong, yet he contributed major findings (just like shakespeare to English literature and Aristotle to philosophy).#

. How does *Vygotsky*'s perspective on cognitive development *differ from Piaget's*?
** [hiddenAnswer]#More sociocultural perspective: Taking social and cultural environment into account (values, beliefs). More on social environment interaction, rather than physical environment. Nice story: Counting balls as a child, figuring out commutativity; Piaget emphasizes action, Vygotsky asks how comes he did that?" PS: He died at age 38.#

. (a) What is Vygotsky's concept of *tools of intellectual adaptation*? (b) How can such tools influence the course of *cognitive development*?
** [hiddenAnswer]#(a) Tools provided by social environment, abstract ones like numbers, alphabets, words; objects to write/calculate/record like pencils, books, computers. (b) .#

. (a) How might the number words of Asian languages help children learn the base-10 number system more easily than American and European children?
(b) What evidence suggests that they do learn the base-10 number system earlier?
** [hiddenAnswer]#(a) Numbers in asian languages (chinese, japanese, korean) have clues already about the base-10 system (instead "eleven" they say "ten one"). (b) Different colored blocks representing 10 and 1, Asian much more effectively distinguish them (80% success, european/US only 10%).#

. How might being a "digital native" influence how children today learn to think?
** [hiddenAnswer]#Digital native: Born into digital media and take it for granted. It comes very natural to them, always available, like a first language, and can take advantage of modern technology.#

. (a) What is the "zone of proximal development", and (b) how does it relate to children's cognitive development?
** [hiddenAnswer]#(a) Shaping is small steps of sub-tasks towards the big task which is very much like scaffolding (guide for gradual increase, letting experience to happen), but this time the unsolvable big task is done in collaboration with a more competent/skilled others. (b) Learn more efficiently. Also think more systematically, than on one's own. It promotes critical thinking through the back-and-forth, internalizing a self-dialogue.#

. How does Vygotsky's "apprentice" view of child contrast with Piaget's "scientist" view?
** [hiddenAnswer]#Vygotsky is more emphasizing that we learn with the help of others, highly depending on the culture/environment we grow up (together/collaboration). Piaget posits that we are more independent, equipped with curiosity to learn by ourselves (alone/exploration).#

. (a) What is information-processing perspective on cognitive development, and (b) how does it differ from Piaget's and Vygotsky's perspectives?
** [hiddenAnswer]#(a) "Mental development in terms of operational changes in basic components of their mental machinery", like a computer, with a CPU (attend; receive info), memory (use; active manipulation) and SSD (remember; passive long-term memory). (b) Info-processing is based on machinery, Piaget on interaction with physical environment, Vygotsky based on social interaction.#

. Through what developmental steps do young children develop the capacity to form episodic memories?
** [hiddenAnswer]#Episodic memories: Autobiography, the story I tell myself, through encoding experiences into words. It seems that there is some symbolic representation shown by "deferred imitation", leading to transient episodic memory as it will be forgotten after some time (no language for encoding available). Short answer: language/conversations, (and brain maturation, especially the prefrontal lobes).#

. (a) How do executive functions and speed of processing change with age during childhood and early adolescence? (b) How might working-memory capacity depend on speed of processing?
** [hiddenAnswer]#(a) Improvements in working memory usage, inhibit behavior/thoughts, task-switching. Increases until peaking at 15. (b) Working-memory is fading away quickly, so by being fast, it leads to more results (capacity).#

. What do children younger than 3 years old understand about other people's minds?
** [hiddenAnswer]#They already have mental constructs about other people's behavior/goals. Even understanding different desires/preferences of others. Experiment with adult played 2 out of 3 toys, then asks to give "the one" and infants gave the one not yet played with. Limitations are other's believes ("which box will X look for the candy" experiment).#

. (a) What evidence suggests that children younger than age 4 usually do not understand that people can hold false beliefs? (b) Why might false beliefs be particularly difficult for young children to understand?
** [hiddenAnswer]#(a) Show crayon box to infants, asked what's inside, child says crayon. Then gave paper sheet, make it look inside the box, shown candles are inside. Children asked what first thought inside, say candles; so why looked inside for crayons to draw on paper? They can't explain. (b) Because it is inherent contradicting: False in reality, yet true in believer's mind.#

. What (a) logic and (b) evidence suggest that engagement in pretend play, especially in role-play with other children, may help children acquire an understanding of *false beliefs*?
** [hiddenAnswer]#(a) Learn difference between make-believe and reality. Pretense (conscious), similar to false beliefs (unconscious), both mental conceptions that differ from reality. Pretend play helps to accept false claims and act on them. (b) Imaginary water in cup and make doll wet, children say it's wet and know it's not really wet. Children who pretend play are better understanding false beliefs, especially useful when having siblings.#

. How does research on people with autism support the premise that the understanding of minds and the understanding of physical objects are fundamentally different abilities?
** [hiddenAnswer]#Autistics are poor on false-belief tests (detect deception), being mindblind (inability to read minds; due to undeveloped theory of mind: understanding ones own/others thoughts/feelings/behaviors). But they do perform good in false-picture tests (picture misrepresent reality).#

. How does research on autism support the idea that an understanding of false beliefs may derive, in part, from prior engagement in pretend play?
** [hiddenAnswer]#Autistic children can't make-belief play, can't pretend play, fail false-belief test (strong correlation). PS: Down syndrome can though.#

. (a) What are the universal characteristics of morphemes? (b) How do morphemes differ from nonverbal signs?
** [hiddenAnswer]#(a) Morphemes: smallest meaningful language unit (not character, more syllable), standing for objects/events/ideas/etc. Universal characteristic 1): pronounceable sound (words, pre-/suffix). E.g. "dog" word and morpheme, "-s" not word but morpheme, "dogs" word and two morphemes. 2) They are arbitrary (no similarity structure and reality) and discrete (no gradiations). (b) Nonverbal signs relate to the object they refer to (similarity), leading to a natural/intuitive understanding. #

. (a) How can any sentence, in any language, be described as a four-level hierarchy? (b) How can grammar be described in relation to that hierarchy?
** [hiddenAnswer]#(a) Levels: Sentences, phrases, words/morphemes, phonemes (vowels/consonant). (b) It defines validity of how lower-level entities can be composed to construct higher-level entities. Phonology: How phonemes arrange morphemes. Morphology: Morphemes combine to words. Syntax: Words arrange to phrases/sentences. Every language has different rules, but every language has them.#

. What does it mean to say that knowledge of grammar is usually implicit rather than explicit?
** [hiddenAnswer]#It's learned without conscious effort. It can be applied but not described. Knowing the difference whether something is right or wrong, without being able to properly explain why.#

. (a) How have researchers shown that very young infants can *distinguish* between subtly different *speech sounds*?
(b) How do infants' abilities to distinguish among such speech sounds *change* during the *second half-year* of their lives?
(c) What is the *value* of these changes?
** [hiddenAnswer]#(a) Sucking on pacifier (=Schnuller) trigger sound playing, get bored suck slower, when new sound, suck faster. Similar for 5+ months infants with sights in combination with sounds (interesting visual stimuli). (b) Better discrimination for sounds representing different phonemes and worse for same phonemes (in native language). (c) Focused improvement of what the environment requires.#

. (a) What is the distinction between *cooing* and *babbling*?
(b) What are the reasons for thinking that these vocalizations are *precursors* to language production?
** [hiddenAnswer]#(a) Cooing is vowels ("ooh-oooh", 2months), and babbling is consonant-and-vowel ("paa-paaa", 6months) sound repetition. (b) By about 8 months, babbles mimic rhythm/pitch patterns of the language around them. Same for sign language.#

. What is evidence that babies begin to understand words well before they begin to speak?
** [hiddenAnswer]#Showing side-by-side video of dad and mom, saying their names, babies would look to the right video. They can also follow simple commands like "get the ball". At least look at the right object when spoken out.#

. How do young children make the link between new words that they hear and appropriate referents in their environments?
** [hiddenAnswer]#Through shared attention and gaze following. Also through cognitive biases/built-in assumptions, narrowing down meaning/referent of a word; e.g. mutual exclusivity assumption, when there is a new, unknown word must refer to unknown referent (not a synonym). "Syntactic bootstrapping" is inferring meaning based on context of sentence, e.g.: "Mommy feeds the foobar", thus it must an animal. Or: "The duck is biffing the bunny", so whatever the duck is doing must be called "biffing". As well as "taxonomic assumption", things are perceptually like the original, whereas possible mistake (all men are "daddy").#

. What are two reasons why children might overextend common nouns that they have learned?
** [hiddenAnswer]#One: Defining new word in terms of just few features of the original referent object (ball = roundness, thus orange called "ball"), a too far extrapolation. Two: Using words for unknown names ("dog" while pointing to cat), a conscious guess.#

. (a) How do children demonstrate knowledge of grammatical rules in their early speech?
(b) How do some of their "mistakes" in grammar confirm that they know the rule and are not just mimicking?
** [hiddenAnswer]#(a) In their telegraphic style speech, the first use nouns and then verbs. (b) Over-regulation (over-generalization): Application of a grammatic rule such as past tense "teach" becomes "teached", or plural with "childs".#

. (a) How did Noam Chomsky link the study of grammar to psychology?
(b) What did he mean by a language-acquisition device?
** [hiddenAnswer]#(a) Through the (grammatical) representations of rules in the mind. (b) Inborn foundations for universal grammar; inborn mechanisms to acquire language quickly/efficiently.#

. How have studies of (a) creole languages and studies of (b) deaf children in Nicaragua supported the idea that children invent grammar in absence of a pre-existing grammatical language?
** [hiddenAnswer]#(a) First colonists developed the "pidgin" language (primitive, grammarless) into a true, grammatical-full language ("creole"). (b) Deaf group of children created their on sign language, whereas youngest contribute most in this process.#

. What evidence supports the view that grammar is learned more readily in early childhood than later in life?
** [hiddenAnswer]#The Genie girl was rescued by the age of 13, after being abused/locked away, never properly learned language/grammar.#

. How do parents in our culture modify their speech to infants?
** [hiddenAnswer]#Using LASS (language-acquisition support system); Simplify speech, helping learn words/grammar, e.g.: pronounce more clearly, more musical voice, greater pitch variation, short sentences, focus here/now, repeat/emphasize outstanding words, using supportive gestures. Motherese/infant-directed speech: Repeating things as in "Oh, you have a ball. A nice ball. What a pretty ball."#

. What evidence suggests that differences in the language environments provided by parents can affect the rates at which infants acquire language?
** [hiddenAnswer]#Adopted children's language development depends significantly on the provided environment (not only biological parents). Parents were given special training for children's language development, those got better than parents without that training.#

. What light has been shed on the LASS by cross-cultural research?
** [hiddenAnswer]#All children acquire language at roughly similar rates (independent of variations in language environment). E.g. Kalikuli people don't speak to babies who cannot speak yet, still they hear lots of talk around them, compensating for lack of verbal interaction.#

. What is the distinction between simultaneous and sequential bilinguals?
** [hiddenAnswer]#Simultaneous are exposed from birth to two languages, get fluent in both. Sequential learn second after mastered the first, which will always stay the dominant one (keep accent in second). Neuroscience confirms that.#

. (a) What are some of the costs and benefits of bilingualism relative to speaking only one language?
(b) Do you think the costs outweigh the benefits?
** [hiddenAnswer]#(a) Delay in syntactic development, smaller vocabularies (yet total vocabulary bigger), slower retrieval times. Improved phonemes recognition, more cultural values sensitive, enhanced executive functions, better task switching/inhibition, delayed decline in executive function. (b) .#

== Think Critically

. (a) How can we know what an infant is thinking about? (b) Why or why not might it be worthwile to study perception and cognition in preverbal infants?
** [hiddenAnswer]#Bar.#

. (a) How are the child's capacities and limitations at each of Piaget's stages of development related to the kind of scheme that is most prominent? (b) How does the child's behavior at each stage promote advancement to the next stage?
** [hiddenAnswer]#Bar.#

. Some theorists propose that children play an active role in their own mental development, whereas others emphasize the role of a child's sociocultural environment in influencing cognitive development Are these approaches complementary or antagonistic to one another?
** [hiddenAnswer]#Bar.#

. To what extent is language development supported by inborn mechanisms and/or the social context?
** [hiddenAnswer]#Bar.#